# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import dispatch_pb2 as dispatch__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in dispatch_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class L3WorkerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Dispatch = channel.unary_unary(
                '/simpler.distributed.v1.L3Worker/Dispatch',
                request_serializer=dispatch__pb2.DispatchReq.SerializeToString,
                response_deserializer=dispatch__pb2.DispatchResp.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/simpler.distributed.v1.L3Worker/Heartbeat',
                request_serializer=dispatch__pb2.Empty.SerializeToString,
                response_deserializer=dispatch__pb2.Health.FromString,
                _registered_method=True)


class L3WorkerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Dispatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_L3WorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Dispatch': grpc.unary_unary_rpc_method_handler(
                    servicer.Dispatch,
                    request_deserializer=dispatch__pb2.DispatchReq.FromString,
                    response_serializer=dispatch__pb2.DispatchResp.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=dispatch__pb2.Empty.FromString,
                    response_serializer=dispatch__pb2.Health.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simpler.distributed.v1.L3Worker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simpler.distributed.v1.L3Worker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class L3Worker(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Dispatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simpler.distributed.v1.L3Worker/Dispatch',
            dispatch__pb2.DispatchReq.SerializeToString,
            dispatch__pb2.DispatchResp.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simpler.distributed.v1.L3Worker/Heartbeat',
            dispatch__pb2.Empty.SerializeToString,
            dispatch__pb2.Health.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class CatalogStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullCallable = channel.unary_unary(
                '/simpler.distributed.v1.Catalog/PullCallable',
                request_serializer=dispatch__pb2.CallableRef.SerializeToString,
                response_deserializer=dispatch__pb2.CallablePayload.FromString,
                _registered_method=True)
        self.PushCallable = channel.unary_unary(
                '/simpler.distributed.v1.Catalog/PushCallable',
                request_serializer=dispatch__pb2.CallablePayload.SerializeToString,
                response_deserializer=dispatch__pb2.Empty.FromString,
                _registered_method=True)


class CatalogServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PullCallable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushCallable(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CatalogServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullCallable': grpc.unary_unary_rpc_method_handler(
                    servicer.PullCallable,
                    request_deserializer=dispatch__pb2.CallableRef.FromString,
                    response_serializer=dispatch__pb2.CallablePayload.SerializeToString,
            ),
            'PushCallable': grpc.unary_unary_rpc_method_handler(
                    servicer.PushCallable,
                    request_deserializer=dispatch__pb2.CallablePayload.FromString,
                    response_serializer=dispatch__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simpler.distributed.v1.Catalog', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simpler.distributed.v1.Catalog', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Catalog(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PullCallable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simpler.distributed.v1.Catalog/PullCallable',
            dispatch__pb2.CallableRef.SerializeToString,
            dispatch__pb2.CallablePayload.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushCallable(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/simpler.distributed.v1.Catalog/PushCallable',
            dispatch__pb2.CallablePayload.SerializeToString,
            dispatch__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class TensorPoolStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.PullTensor = channel.unary_stream(
                '/simpler.distributed.v1.TensorPool/PullTensor',
                request_serializer=dispatch__pb2.TensorHandle.SerializeToString,
                response_deserializer=dispatch__pb2.TensorChunk.FromString,
                _registered_method=True)
        self.PushTensor = channel.stream_unary(
                '/simpler.distributed.v1.TensorPool/PushTensor',
                request_serializer=dispatch__pb2.TensorChunk.SerializeToString,
                response_deserializer=dispatch__pb2.TensorHandle.FromString,
                _registered_method=True)


class TensorPoolServicer(object):
    """Missing associated documentation comment in .proto file."""

    def PullTensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def PushTensor(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TensorPoolServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'PullTensor': grpc.unary_stream_rpc_method_handler(
                    servicer.PullTensor,
                    request_deserializer=dispatch__pb2.TensorHandle.FromString,
                    response_serializer=dispatch__pb2.TensorChunk.SerializeToString,
            ),
            'PushTensor': grpc.stream_unary_rpc_method_handler(
                    servicer.PushTensor,
                    request_deserializer=dispatch__pb2.TensorChunk.FromString,
                    response_serializer=dispatch__pb2.TensorHandle.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'simpler.distributed.v1.TensorPool', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('simpler.distributed.v1.TensorPool', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TensorPool(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def PullTensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/simpler.distributed.v1.TensorPool/PullTensor',
            dispatch__pb2.TensorHandle.SerializeToString,
            dispatch__pb2.TensorChunk.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def PushTensor(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/simpler.distributed.v1.TensorPool/PushTensor',
            dispatch__pb2.TensorChunk.SerializeToString,
            dispatch__pb2.TensorHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
