// Kernel Function: exp_recv_y_write
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_recv_y_write(__gm__ float* v1, __gm__ bfloat16_t* v2, int32_t v3, int32_t v4) {
  RoundMode v5 = RoundMode::CAST_ROUND;
  unsigned v6 = 0;
  const int32_t v7 = 4096;
  const int32_t v8 = 1;
  const int32_t v9 = 512;
  const int32_t v10 = 16;
  const int64_t v11 = 32768;
  const int64_t v12 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v13 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v14 = (uint64_t) v12;
  TASSIGN(v13, v14);
  pto::Shape<1, 1, 1, 16, 512> v15 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v16 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v17 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v8), v15, v16);
  TLOAD(v13, v17);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v18 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v19 = (uint64_t) v11;
  TASSIGN(v18, v19);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v18, v13, v5);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 512> v20 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v21 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v22 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v6 + (unsigned) v3 * (unsigned) v7 + (unsigned) v4 * (unsigned) v8), v20, v21);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v22, v18);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: y_2d_v1_inline17__ssa_v0
    __gm__ Tensor* y_2d_v1_inline17__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* y_2d_v1_inline17__ssa_v0 = reinterpret_cast<__gm__ float*>(y_2d_v1_inline17__ssa_v0_tensor->buffer.addr) + y_2d_v1_inline17__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_y_flat_inline53__iter_v5
    __gm__ Tensor* recv_y_flat_inline53__iter_v5_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* recv_y_flat_inline53__iter_v5 = reinterpret_cast<__gm__ bfloat16_t*>(recv_y_flat_inline53__iter_v5_tensor->buffer.addr) + recv_y_flat_inline53__iter_v5_tensor->start_offset;

    // Unpack scalar: flat_t0_inline40__ssa_v0
    union { uint64_t u64; int64_t val; } flat_t0_inline40__ssa_v0_conv;
    flat_t0_inline40__ssa_v0_conv.u64 = args[2];
    int64_t flat_t0_inline40__ssa_v0 = flat_t0_inline40__ssa_v0_conv.val;

    // Unpack scalar: d0_inline49__idx_v0
    union { uint64_t u64; int64_t val; } d0_inline49__idx_v0_conv;
    d0_inline49__idx_v0_conv.u64 = args[3];
    int64_t d0_inline49__idx_v0 = d0_inline49__idx_v0_conv.val;

    // Forward to ptoas-generated function
    exp_recv_y_write(y_2d_v1_inline17__ssa_v0, recv_y_flat_inline53__iter_v5, flat_t0_inline40__ssa_v0, d0_inline49__idx_v0);
}
