// Kernel Function: exp_h_q
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_h_q(__gm__ float* v1, __gm__ int8_t* v2, __gm__ float* v3) {
  RoundMode v4 = RoundMode::CAST_TRUNC;
  RoundMode v5 = RoundMode::CAST_ROUND;
  unsigned v6 = 0;
  const float v7 = 127.0f;
  const int32_t v8 = 256;
  const int32_t v9 = 0;
  const float v10 = 9.99999974E-5f;
  const int32_t v11 = 1;
  const int32_t v12 = 4096;
  const int32_t v13 = 16;
  const int64_t v14 = 24640;
  const int64_t v15 = 16448;
  const int64_t v16 = 64;
  const int64_t v17 = 0;
  const int64_t v18 = 61568;
  const int64_t v19 = 45184;
  const int64_t v20 = 28800;
  const int64_t v21 = 28736;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v22 = (size_t) v12;
  size_t v23 = (size_t) v9;
  size_t v24 = (size_t) v8;
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v26 = (uint64_t) v21;
  TASSIGN(v25, v26);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  TEXPANDS(v25, v10);
  for (size_t v27 = v23; v27 < v22; v27 += v24) {
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v29 = (uint64_t) v20;
    TASSIGN(v28, v29);
    pto::Shape<1, 1, 1, 16, 256> v30 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v31 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v32 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v12 + (unsigned) ((int32_t) v27) * (unsigned) v11), v30, v31);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v28, v32);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v34 = (uint64_t) v19;
    TASSIGN(v33, v34);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TNEG(v33, v28);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v36 = (uint64_t) v20;
    TASSIGN(v35, v36);
    pipe_barrier(PIPE_V);
    TMAX(v35, v28, v33);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v38 = (uint64_t) v19;
    TASSIGN(v37, v38);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
    uint64_t v40 = (uint64_t) v18;
    TASSIGN(v39, v40);
    pipe_barrier(PIPE_V);
    TROWMAX(v39, v35, v37);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v42 = (uint64_t) v18;
    TASSIGN(v41, v42);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v44 = (uint64_t) v21;
    TASSIGN(v43, v44);
    pipe_barrier(PIPE_V);
    TMAX(v43, v25, v41);
  }
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v46 = (uint64_t) v17;
  TASSIGN(v45, v46);
  TEXPANDS(v45, v7);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v48 = (uint64_t) v21;
  TASSIGN(v47, v48);
  pipe_barrier(PIPE_V);
  TDIV(v47, v45, v25);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v50 = (uint64_t) v17;
  TASSIGN(v49, v50);
  pipe_barrier(PIPE_V);
  TRECIP(v49, v47);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v51 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v52 = (uint64_t) v17;
  TASSIGN(v51, v52);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v53 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v54 = (uint64_t) v21;
  TASSIGN(v53, v54);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  for (size_t v55 = v23; v55 < v22; v55 += v24) {
    int32_t v56 = (int32_t) v55;
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v58 = (uint64_t) v20;
    TASSIGN(v57, v58);
    pto::Shape<1, 1, 1, 16, 256> v59 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v60 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v61 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v12 + (unsigned) v56 * (unsigned) v11), v59, v60);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v57, v61);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v63 = (uint64_t) v20;
    TASSIGN(v62, v63);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TROWEXPANDMUL(v62, v57, v53);
    Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v65 = (uint64_t) v16;
    TASSIGN(v64, v65);
    pipe_barrier(PIPE_V);
    TCVT(v64, v62, v5);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v67 = (uint64_t) v15;
    TASSIGN(v66, v67);
    pipe_barrier(PIPE_V);
    TCVT(v66, v64, v5);
    Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v69 = (uint64_t) v14;
    TASSIGN(v68, v69);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TCVT(v68, v66, v4);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pto::Shape<1, 1, 1, 16, 256> v70 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v71 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v72 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v6 + v6 * (unsigned) v12 + (unsigned) v56 * (unsigned) v11), v70, v71);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v72, v68);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  }
  pto::Shape<1, 1, 1, 16, 1> v73 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v74 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v75 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v6 + v6 * (unsigned) v11 + v6 * (unsigned) v13), v73, v74);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v75, v51);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: h_tile_fp32_inline18__rv_v2
    __gm__ Tensor* h_tile_fp32_inline18__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* h_tile_fp32_inline18__rv_v2 = reinterpret_cast<__gm__ float*>(h_tile_fp32_inline18__rv_v2_tensor->buffer.addr) + h_tile_fp32_inline18__rv_v2_tensor->start_offset;

    // Unpack tensor: h_tile_i8_inline92__ssa_v0
    __gm__ Tensor* h_tile_i8_inline92__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* h_tile_i8_inline92__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(h_tile_i8_inline92__ssa_v0_tensor->buffer.addr) + h_tile_i8_inline92__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Forward to ptoas-generated function
    exp_h_q(h_tile_fp32_inline18__rv_v2, h_tile_i8_inline92__ssa_v0, ret0__out);
}
