// Kernel Function: exp_w2_dequant
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_w2_dequant(__gm__ int32_t* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, int32_t v5, int32_t v6) {
  RoundMode v7 = RoundMode::CAST_NONE;
  unsigned v8 = 0;
  const int32_t v9 = 8192;
  const int32_t v10 = 4096;
  const int32_t v11 = 512;
  const int32_t v12 = 16;
  const int32_t v13 = 1;
  const int64_t v14 = 34880;
  const int64_t v15 = 32832;
  const int64_t v16 = 32768;
  const int64_t v17 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v18 = Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v19 = (uint64_t) v17;
  TASSIGN(v18, v19);
  pto::Shape<1, 1, 1, 16, 512> v20 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v21 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v22 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v1 + ((v8 + v8 * (unsigned) v9) + v8 * (unsigned) v11 + v8 * (unsigned) v13), v20, v21);
  TLOAD(v18, v22);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v13);
  uint64_t v24 = (uint64_t) v16;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 16, 1> v25 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v26 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v8 + v8 * (unsigned) v13 + v8 * (unsigned) v12), v25, v26);
  TLOAD(v23, v27);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v29 = (uint64_t) v17;
  TASSIGN(v28, v29);
  Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v31 = (uint64_t) v15;
  TASSIGN(v30, v31);
  pto::Shape<1, 1, 1, 1, 512> v32 = pto::Shape<1, 1, 1, 1, 512>();
  pto::Stride<4096, 4096, 4096, 4096, 1> v33 = pto::Stride<4096, 4096, 4096, 4096, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v34 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v2 + (v8 + (unsigned) v5 * (unsigned) v10 + (unsigned) v6 * (unsigned) v13), v32, v33);
  TLOAD(v30, v34);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v36 = (uint64_t) v14;
  TASSIGN(v35, v36);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v35, v28, v7);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v38 = (uint64_t) v14;
  TASSIGN(v37, v38);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TROWEXPANDMUL(v37, v35, v23);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v40 = (uint64_t) v14;
  TASSIGN(v39, v40);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  TCOLEXPANDMUL(v39, v37, v30);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 512> v41 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v42 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v43 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v4 + (v8 + v8 * (unsigned) v11 + v8 * (unsigned) v13), v41, v42);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v43, v39);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: y_acc_inline109__rv_v2
    __gm__ Tensor* y_acc_inline109__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int32_t* y_acc_inline109__rv_v2 = reinterpret_cast<__gm__ int32_t*>(y_acc_inline109__rv_v2_tensor->buffer.addr) + y_acc_inline109__rv_v2_tensor->start_offset;

    // Unpack tensor: expert_w2_scale__ssa_v0
    __gm__ Tensor* expert_w2_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* expert_w2_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(expert_w2_scale__ssa_v0_tensor->buffer.addr) + expert_w2_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_tile_scale_dq_inline63__ssa_v0
    __gm__ Tensor* h_tile_scale_dq_inline63__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* h_tile_scale_dq_inline63__ssa_v0 = reinterpret_cast<__gm__ float*>(h_tile_scale_dq_inline63__ssa_v0_tensor->buffer.addr) + h_tile_scale_dq_inline63__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: local_i_inline67__idx_v0
    union { uint64_t u64; int64_t val; } local_i_inline67__idx_v0_conv;
    local_i_inline67__idx_v0_conv.u64 = args[4];
    int64_t local_i_inline67__idx_v0 = local_i_inline67__idx_v0_conv.val;

    // Unpack scalar: d0_inline49__idx_v0
    union { uint64_t u64; int64_t val; } d0_inline49__idx_v0_conv;
    d0_inline49__idx_v0_conv.u64 = args[5];
    int64_t d0_inline49__idx_v0 = d0_inline49__idx_v0_conv.val;

    // Forward to ptoas-generated function
    exp_w2_dequant(y_acc_inline109__rv_v2, expert_w2_scale__ssa_v0, h_tile_scale_dq_inline63__ssa_v0, ret0__out, local_i_inline67__idx_v0, d0_inline49__idx_v0);
}
