// Kernel Function: exp_swiglu_mask
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_swiglu_mask(__gm__ float* v1, __gm__ float* v2, int32_t v3, int32_t v4) {
  unsigned v5 = 0;
  const int32_t v6 = 4096;
  const int32_t v7 = 1;
  const int32_t v8 = 256;
  const int32_t v9 = 16;
  const int64_t v10 = 16384;
  const int64_t v11 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v12 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
  uint64_t v13 = (uint64_t) v11;
  TASSIGN(v12, v13);
  pto::Shape<1, 1, 1, 16, 256> v14 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v15 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v16 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v8 + v5 * (unsigned) v7), v14, v15);
  TLOAD(v12, v16);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  v12.SetValidShape(v3, v8);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null> v17 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Zero, CompactMode::Null>(v9, v8);
  uint64_t v18 = (uint64_t) v10;
  TASSIGN(v17, v18);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TFILLPAD(v17, v12);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v19 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v20 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v21 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v5 + v5 * (unsigned) v6 + (unsigned) v4 * (unsigned) v7), v19, v20);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v21, v17);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: h_chunk_inline89__ssa_v0
    __gm__ Tensor* h_chunk_inline89__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* h_chunk_inline89__ssa_v0 = reinterpret_cast<__gm__ float*>(h_chunk_inline89__ssa_v0_tensor->buffer.addr) + h_chunk_inline89__ssa_v0_tensor->start_offset;

    // Unpack tensor: h_tile_fp32_inline18__iter_v1
    __gm__ Tensor* h_tile_fp32_inline18__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* h_tile_fp32_inline18__iter_v1 = reinterpret_cast<__gm__ float*>(h_tile_fp32_inline18__iter_v1_tensor->buffer.addr) + h_tile_fp32_inline18__iter_v1_tensor->start_offset;

    // Unpack scalar: valid_rows_inline73__ssa_v0
    union { uint64_t u64; int64_t val; } valid_rows_inline73__ssa_v0_conv;
    valid_rows_inline73__ssa_v0_conv.u64 = args[2];
    int64_t valid_rows_inline73__ssa_v0 = valid_rows_inline73__ssa_v0_conv.val;

    // Unpack scalar: n0_inline72__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline72__idx_v0_conv;
    n0_inline72__idx_v0_conv.u64 = args[3];
    int64_t n0_inline72__idx_v0 = n0_inline72__idx_v0_conv.val;

    // Forward to ptoas-generated function
    exp_swiglu_mask(h_chunk_inline89__ssa_v0, h_tile_fp32_inline18__iter_v1, valid_rows_inline73__ssa_v0, n0_inline72__idx_v0);
}
