// Kernel Function: exp_gate_up_dequant
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_gate_up_dequant(__gm__ int32_t* v1, __gm__ int32_t* v2, __gm__ float* v3, __gm__ float* v4, __gm__ float* v5, __gm__ float* v6, __gm__ float* v7, int32_t v8, int32_t v9) {
  RoundMode v10 = RoundMode::CAST_NONE;
  unsigned v11 = 0;
  const int32_t v12 = 4096;
  const int32_t v13 = 256;
  const int32_t v14 = 16;
  const int32_t v15 = 1;
  const int64_t v16 = 18432;
  const int64_t v17 = 2048;
  const int64_t v18 = 1024;
  const int64_t v19 = 0;
  const int64_t v20 = 67584;
  const int64_t v21 = 51200;
  const int64_t v22 = 34816;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v24 = (uint64_t) v22;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 16, 256> v25 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v26 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v27 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v1 + ((v11 + v11 * (unsigned) v12) + v11 * (unsigned) v13 + v11 * (unsigned) v15), v25, v26);
  TLOAD(v23, v27);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v29 = (uint64_t) v21;
  TASSIGN(v28, v29);
  pto::Shape<1, 1, 1, 16, 256> v30 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v31 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v32 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v2 + ((v11 + v11 * (unsigned) v12) + v11 * (unsigned) v13 + v11 * (unsigned) v15), v30, v31);
  TLOAD(v28, v32);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v15);
  uint64_t v34 = (uint64_t) v20;
  TASSIGN(v33, v34);
  pto::Shape<1, 1, 1, 16, 1> v35 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v36 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v5 + (v11 + v11 * (unsigned) v15 + v11 * (unsigned) v14), v35, v36);
  TLOAD(v33, v37);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v39 = (uint64_t) v22;
  TASSIGN(v38, v39);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v40 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v41 = (uint64_t) v21;
  TASSIGN(v40, v41);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v42 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
  uint64_t v43 = (uint64_t) v19;
  TASSIGN(v42, v43);
  pto::Shape<1, 1, 1, 1, 256> v44 = pto::Shape<1, 1, 1, 1, 256>();
  pto::Stride<4096, 4096, 4096, 4096, 1> v45 = pto::Stride<4096, 4096, 4096, 4096, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v46 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v3 + (v11 + (unsigned) v8 * (unsigned) v12 + (unsigned) v9 * (unsigned) v15), v44, v45);
  TLOAD(v42, v46);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
  uint64_t v48 = (uint64_t) v18;
  TASSIGN(v47, v48);
  pto::Shape<1, 1, 1, 1, 256> v49 = pto::Shape<1, 1, 1, 1, 256>();
  pto::Stride<4096, 4096, 4096, 4096, 1> v50 = pto::Stride<4096, 4096, 4096, 4096, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v51 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v4 + (v11 + (unsigned) v8 * (unsigned) v12 + (unsigned) v9 * (unsigned) v15), v49, v50);
  TLOAD(v47, v51);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v53 = (uint64_t) v17;
  TASSIGN(v52, v53);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v52, v38, v10);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v55 = (uint64_t) v16;
  TASSIGN(v54, v55);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCVT(v54, v40, v10);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v57 = (uint64_t) v17;
  TASSIGN(v56, v57);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  TROWEXPANDMUL(v56, v52, v33);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v59 = (uint64_t) v17;
  TASSIGN(v58, v59);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
  TCOLEXPANDMUL(v58, v56, v42);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v61 = (uint64_t) v16;
  TASSIGN(v60, v61);
  TROWEXPANDMUL(v60, v54, v33);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v13);
  uint64_t v63 = (uint64_t) v16;
  TASSIGN(v62, v63);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
  TCOLEXPANDMUL(v62, v60, v47);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  pto::Shape<1, 1, 1, 16, 256> v64 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v65 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v66 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v6 + (v11 + v11 * (unsigned) v13 + v11 * (unsigned) v15), v64, v65);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v66, v58);
  pto::Shape<1, 1, 1, 16, 256> v67 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v68 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v69 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v7 + (v11 + v11 * (unsigned) v13 + v11 * (unsigned) v15), v67, v68);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v69, v62);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: gate_acc_inline69__rv_v2
    __gm__ Tensor* gate_acc_inline69__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int32_t* gate_acc_inline69__rv_v2 = reinterpret_cast<__gm__ int32_t*>(gate_acc_inline69__rv_v2_tensor->buffer.addr) + gate_acc_inline69__rv_v2_tensor->start_offset;

    // Unpack tensor: up_acc_inline46__rv_v2
    __gm__ Tensor* up_acc_inline46__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* up_acc_inline46__rv_v2 = reinterpret_cast<__gm__ int32_t*>(up_acc_inline46__rv_v2_tensor->buffer.addr) + up_acc_inline46__rv_v2_tensor->start_offset;

    // Unpack tensor: expert_w1_scale__ssa_v0
    __gm__ Tensor* expert_w1_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* expert_w1_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(expert_w1_scale__ssa_v0_tensor->buffer.addr) + expert_w1_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: expert_w3_scale__ssa_v0
    __gm__ Tensor* expert_w3_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* expert_w3_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(expert_w3_scale__ssa_v0_tensor->buffer.addr) + expert_w3_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_x_scale_dq_inline29__ssa_v0
    __gm__ Tensor* recv_x_scale_dq_inline29__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* recv_x_scale_dq_inline29__ssa_v0 = reinterpret_cast<__gm__ float*>(recv_x_scale_dq_inline29__ssa_v0_tensor->buffer.addr) + recv_x_scale_dq_inline29__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack tensor: ret1__out
    __gm__ Tensor* ret1__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[6]);
    __gm__ float* ret1__out = reinterpret_cast<__gm__ float*>(ret1__out_tensor->buffer.addr) + ret1__out_tensor->start_offset;

    // Unpack scalar: local_i_inline67__idx_v0
    union { uint64_t u64; int64_t val; } local_i_inline67__idx_v0_conv;
    local_i_inline67__idx_v0_conv.u64 = args[7];
    int64_t local_i_inline67__idx_v0 = local_i_inline67__idx_v0_conv.val;

    // Unpack scalar: n0_inline72__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline72__idx_v0_conv;
    n0_inline72__idx_v0_conv.u64 = args[8];
    int64_t n0_inline72__idx_v0 = n0_inline72__idx_v0_conv.val;

    // Forward to ptoas-generated function
    exp_gate_up_dequant(gate_acc_inline69__rv_v2, up_acc_inline46__rv_v2, expert_w1_scale__ssa_v0, expert_w3_scale__ssa_v0, recv_x_scale_dq_inline29__ssa_v0, ret0__out, ret1__out, local_i_inline67__idx_v0, n0_inline72__idx_v0);
}
