// Kernel Function: exp_swiglu
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_swiglu(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, int32_t v5) {
  unsigned v6 = 0;
  const float v7 = 1.0f;
  const int32_t v8 = 1;
  const int32_t v9 = 256;
  const int32_t v10 = 16;
  const int64_t v11 = 0;
  const int64_t v12 = 49216;
  const int64_t v13 = 32832;
  const int64_t v14 = 16448;
  const int64_t v15 = 64;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v16 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v17 = (uint64_t) v15;
  TASSIGN(v16, v17);
  pto::Shape<1, 1, 1, 16, 256> v18 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v19 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v20 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v8), v18, v19);
  TLOAD(v16, v20);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v21 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v22 = (uint64_t) v14;
  TASSIGN(v21, v22);
  pto::Shape<1, 1, 1, 16, 256> v23 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v24 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v25 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v2 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v8), v23, v24);
  TLOAD(v21, v25);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v27 = (uint64_t) v13;
  TASSIGN(v26, v27);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TNEG(v26, v16);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v29 = (uint64_t) v13;
  TASSIGN(v28, v29);
  pipe_barrier(PIPE_V);
  TEXP(v28, v26);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v31 = (uint64_t) v13;
  TASSIGN(v30, v31);
  pipe_barrier(PIPE_V);
  TADDS(v30, v28, v7);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v33 = (uint64_t) v12;
  TASSIGN(v32, v33);
  pipe_barrier(PIPE_V);
  TRECIP(v32, v30);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v35 = (uint64_t) v15;
  TASSIGN(v34, v35);
  pipe_barrier(PIPE_V);
  TMUL(v34, v16, v32);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v37 = (uint64_t) v15;
  TASSIGN(v36, v37);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TMUL(v36, v34, v21);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v39 = (uint64_t) v11;
  TASSIGN(v38, v39);
  pto::Shape<1, 1, 1, 16, 1> v40 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 256> v41 = pto::Stride<16, 16, 16, 1, 256>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 256>, pto::Layout::DN> v42 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 256>, pto::Layout::DN>(v3 + (v6 + (unsigned) v5 * (unsigned) v8 + v6 * (unsigned) v9), v40, v41);
  TLOAD(v38, v42);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v44 = (uint64_t) v15;
  TASSIGN(v43, v44);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  pipe_barrier(PIPE_V);
  TROWEXPANDMUL(v43, v36, v38);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v45 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v46 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v47 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v4 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v8), v45, v46);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v47, v43);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: gate_2d_v1_inline7__ssa_v0
    __gm__ Tensor* gate_2d_v1_inline7__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* gate_2d_v1_inline7__ssa_v0 = reinterpret_cast<__gm__ float*>(gate_2d_v1_inline7__ssa_v0_tensor->buffer.addr) + gate_2d_v1_inline7__ssa_v0_tensor->start_offset;

    // Unpack tensor: up_2d_v1_inline78__ssa_v0
    __gm__ Tensor* up_2d_v1_inline78__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* up_2d_v1_inline78__ssa_v0 = reinterpret_cast<__gm__ float*>(up_2d_v1_inline78__ssa_v0_tensor->buffer.addr) + up_2d_v1_inline78__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_weights_flat_inline62__ssa_v0
    __gm__ Tensor* recv_weights_flat_inline62__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* recv_weights_flat_inline62__ssa_v0 = reinterpret_cast<__gm__ float*>(recv_weights_flat_inline62__ssa_v0_tensor->buffer.addr) + recv_weights_flat_inline62__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: flat_t0_inline40__ssa_v0
    union { uint64_t u64; int64_t val; } flat_t0_inline40__ssa_v0_conv;
    flat_t0_inline40__ssa_v0_conv.u64 = args[4];
    int64_t flat_t0_inline40__ssa_v0 = flat_t0_inline40__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    exp_swiglu(gate_2d_v1_inline7__ssa_v0, up_2d_v1_inline78__ssa_v0, recv_weights_flat_inline62__ssa_v0, ret0__out, flat_t0_inline40__ssa_v0);
}
