// Kernel Function: ffn_norm_apply
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void ffn_norm_apply(__gm__ float* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, __gm__ bfloat16_t* v4, __gm__ bfloat16_t* v5, int32_t v6) {
  RoundMode v7 = RoundMode::CAST_RINT;
  RoundMode v8 = RoundMode::CAST_ROUND;
  unsigned v9 = 0;
  const int32_t v10 = 512;
  const int32_t v11 = 4096;
  const int32_t v12 = 16;
  const int32_t v13 = 1;
  const int64_t v14 = 49216;
  const int64_t v15 = 16448;
  const int64_t v16 = 64;
  const int64_t v17 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  int32_t v18 = (int32_t) ((uint32_t) v6 * (uint32_t) v10);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v19 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v20 = (uint64_t) v17;
  TASSIGN(v19, v20);
  pto::Shape<1, 1, 1, 1, 16> v21 = pto::Shape<1, 1, 1, 1, 16>();
  pto::Stride<16, 16, 16, 16, 1> v22 = pto::Stride<16, 16, 16, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v23 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v1 + (v9 + v9 * (unsigned) v12 + v9 * (unsigned) v13), v21, v22);
  TLOAD(v19, v23);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v24 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v13);
  uint64_t v25 = (uint64_t) v17;
  TASSIGN(v24, v25);
  Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v27 = (uint64_t) v16;
  TASSIGN(v26, v27);
  pto::Shape<1, 1, 1, 16, 512> v28 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v29 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v30 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v9 + v9 * (unsigned) v11 + (unsigned) v18 * (unsigned) v13), v28, v29);
  TLOAD(v26, v30);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v32 = (uint64_t) v15;
  TASSIGN(v31, v32);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v31, v26, v8);
  Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v10);
  uint64_t v34 = (uint64_t) v14;
  TASSIGN(v33, v34);
  pto::Shape<1, 1, 1, 1, 512> v35 = pto::Shape<1, 1, 1, 1, 512>();
  pto::Stride<512, 512, 512, 512, 1> v36 = pto::Stride<512, 512, 512, 512, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v3 + (v9 + (unsigned) v18 * (unsigned) v13), v35, v36);
  TLOAD(v33, v37);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v10);
  uint64_t v39 = (uint64_t) v14;
  TASSIGN(v38, v39);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v40 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v41 = (uint64_t) v15;
  TASSIGN(v40, v41);
  pipe_barrier(PIPE_V);
  TROWEXPANDMUL(v40, v31, v24);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v42 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v43 = (uint64_t) v15;
  TASSIGN(v42, v43);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v42, v40, v38);
  Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v44 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v10);
  uint64_t v45 = (uint64_t) v16;
  TASSIGN(v44, v45);
  pipe_barrier(PIPE_V);
  TCVT(v44, v42, v7);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 512> v46 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v47 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v48 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v4 + (v9 + v9 * (unsigned) v11 + (unsigned) v18 * (unsigned) v13), v46, v47);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v48, v44);
  pto::Shape<1, 1, 1, 16, 512> v49 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v50 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v51 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v5 + (v9 + v9 * (unsigned) v11 + (unsigned) v18 * (unsigned) v13), v49, v50);
  TSTORE(v51, v44);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: inv_rms_inline126__ssa_v1
    __gm__ Tensor* inv_rms_inline126__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* inv_rms_inline126__ssa_v1 = reinterpret_cast<__gm__ float*>(inv_rms_inline126__ssa_v1_tensor->buffer.addr) + inv_rms_inline126__ssa_v1_tensor->start_offset;

    // Unpack tensor: x_mixed_flat_inline127__ssa_v0
    __gm__ Tensor* x_mixed_flat_inline127__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* x_mixed_flat_inline127__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(x_mixed_flat_inline127__ssa_v0_tensor->buffer.addr) + x_mixed_flat_inline127__ssa_v0_tensor->start_offset;

    // Unpack tensor: norm_w__ssa_v0
    __gm__ Tensor* norm_w__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* norm_w__ssa_v0 = reinterpret_cast<__gm__ float*>(norm_w__ssa_v0_tensor->buffer.addr) + norm_w__ssa_v0_tensor->start_offset;

    // Unpack tensor: x_norm_bf16_inline111__iter_v1
    __gm__ Tensor* x_norm_bf16_inline111__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ bfloat16_t* x_norm_bf16_inline111__iter_v1 = reinterpret_cast<__gm__ bfloat16_t*>(x_norm_bf16_inline111__iter_v1_tensor->buffer.addr) + x_norm_bf16_inline111__iter_v1_tensor->start_offset;

    // Unpack tensor: x_norm__iter_v1
    __gm__ Tensor* x_norm__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ bfloat16_t* x_norm__iter_v1 = reinterpret_cast<__gm__ bfloat16_t*>(x_norm__iter_v1_tensor->buffer.addr) + x_norm__iter_v1_tensor->start_offset;

    // Unpack scalar: db_inline125__idx_v0
    union { uint64_t u64; int64_t val; } db_inline125__idx_v0_conv;
    db_inline125__idx_v0_conv.u64 = args[5];
    int64_t db_inline125__idx_v0 = db_inline125__idx_v0_conv.val;

    // Forward to ptoas-generated function
    ffn_norm_apply(inv_rms_inline126__ssa_v1, x_mixed_flat_inline127__ssa_v0, norm_w__ssa_v0, x_norm_bf16_inline111__iter_v1, x_norm__iter_v1, db_inline125__idx_v0);
}
