// Kernel Function: ffn_norm_rms
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void ffn_norm_rms(__gm__ bfloat16_t* v1, __gm__ float* v2) {
  RoundMode v3 = RoundMode::CAST_ROUND;
  unsigned v4 = 0;
  const float v5 = 9.99999997E-7f;
  const float v6 = 2.44140625E-4f;
  const int32_t v7 = 1536;
  const int32_t v8 = 1024;
  const int32_t v9 = 512;
  const int32_t v10 = 4;
  const int32_t v11 = 8;
  const int32_t v12 = 0;
  const float v13 = 0.0f;
  const int32_t v14 = 1;
  const int32_t v15 = 4096;
  const int32_t v16 = 16;
  const int64_t v17 = 64;
  const int64_t v18 = 0;
  const int64_t v19 = 98496;
  const int64_t v20 = 65728;
  const int64_t v21 = 49344;
  const int64_t v22 = 32960;
  const int64_t v23 = 16576;
  const int64_t v24 = 192;
  const int64_t v25 = 128;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
  uint64_t v27 = (uint64_t) v25;
  TASSIGN(v26, v27);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  TEXPANDS(v26, v13);
  for (size_t v28 = (size_t) v12; v28 < ((size_t) v11); v28 += (size_t) v10) {
    int32_t v29 = (int32_t) ((uint32_t) ((int32_t) v28) * (uint32_t) v9);
    Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v31 = (uint64_t) v24;
    TASSIGN(v30, v31);
    pto::Shape<1, 1, 1, 16, 512> v32 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v33 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v34 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v4 + v4 * (unsigned) v15 + (unsigned) v29 * (unsigned) v14), v32, v33);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v30, v34);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v36 = (uint64_t) v23;
    TASSIGN(v35, v36);
    pto::Shape<1, 1, 1, 16, 512> v37 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v38 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v39 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v4 + v4 * (unsigned) v15 + (unsigned) ((int32_t) (uint32_t) v29 + (uint32_t) v9) * (unsigned) v14), v37, v38);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    TLOAD(v35, v39);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v40 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v41 = (uint64_t) v22;
    TASSIGN(v40, v41);
    pto::Shape<1, 1, 1, 16, 512> v42 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v43 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v44 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v4 + v4 * (unsigned) v15 + (unsigned) ((int32_t) (uint32_t) v29 + (uint32_t) v8) * (unsigned) v14), v42, v43);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v40, v44);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v46 = (uint64_t) v21;
    TASSIGN(v45, v46);
    pto::Shape<1, 1, 1, 16, 512> v47 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v48 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v49 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v4 + v4 * (unsigned) v15 + (unsigned) ((int32_t) (uint32_t) v29 + (uint32_t) v7) * (unsigned) v14), v47, v48);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
    TLOAD(v45, v49);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v51 = (uint64_t) v20;
    TASSIGN(v50, v51);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v50, v30, v3);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v53 = (uint64_t) v20;
    TASSIGN(v52, v53);
    pipe_barrier(PIPE_V);
    TMUL(v52, v50, v50);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v55 = (uint64_t) v19;
    TASSIGN(v54, v55);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v14);
    uint64_t v57 = (uint64_t) v18;
    TASSIGN(v56, v57);
    pipe_barrier(PIPE_V);
    TROWSUM(v56, v52, v54);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v59 = (uint64_t) v18;
    TASSIGN(v58, v59);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v61 = (uint64_t) v17;
    TASSIGN(v60, v61);
    pipe_barrier(PIPE_V);
    TADD(v60, v26, v58);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v63 = (uint64_t) v20;
    TASSIGN(v62, v63);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TCVT(v62, v35, v3);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v65 = (uint64_t) v20;
    TASSIGN(v64, v65);
    pipe_barrier(PIPE_V);
    TMUL(v64, v62, v62);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v67 = (uint64_t) v19;
    TASSIGN(v66, v67);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v14);
    uint64_t v69 = (uint64_t) v18;
    TASSIGN(v68, v69);
    pipe_barrier(PIPE_V);
    TROWSUM(v68, v64, v66);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v71 = (uint64_t) v18;
    TASSIGN(v70, v71);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v73 = (uint64_t) v17;
    TASSIGN(v72, v73);
    pipe_barrier(PIPE_V);
    TADD(v72, v60, v70);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v75 = (uint64_t) v20;
    TASSIGN(v74, v75);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    TCVT(v74, v40, v3);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v77 = (uint64_t) v20;
    TASSIGN(v76, v77);
    pipe_barrier(PIPE_V);
    TMUL(v76, v74, v74);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v78 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v79 = (uint64_t) v19;
    TASSIGN(v78, v79);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v14);
    uint64_t v81 = (uint64_t) v18;
    TASSIGN(v80, v81);
    pipe_barrier(PIPE_V);
    TROWSUM(v80, v76, v78);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v82 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v83 = (uint64_t) v18;
    TASSIGN(v82, v83);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v85 = (uint64_t) v17;
    TASSIGN(v84, v85);
    pipe_barrier(PIPE_V);
    TADD(v84, v72, v82);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v87 = (uint64_t) v20;
    TASSIGN(v86, v87);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    TCVT(v86, v45, v3);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v89 = (uint64_t) v20;
    TASSIGN(v88, v89);
    pipe_barrier(PIPE_V);
    TMUL(v88, v86, v86);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v90 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v91 = (uint64_t) v19;
    TASSIGN(v90, v91);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v92 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v16, v14);
    uint64_t v93 = (uint64_t) v18;
    TASSIGN(v92, v93);
    pipe_barrier(PIPE_V);
    TROWSUM(v92, v88, v90);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v94 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v95 = (uint64_t) v18;
    TASSIGN(v94, v95);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v96 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
    uint64_t v97 = (uint64_t) v25;
    TASSIGN(v96, v97);
    pipe_barrier(PIPE_V);
    TADD(v96, v84, v94);
  }
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v98 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
  uint64_t v99 = (uint64_t) v25;
  TASSIGN(v98, v99);
  pipe_barrier(PIPE_V);
  TMULS(v98, v26, v6);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v100 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
  uint64_t v101 = (uint64_t) v25;
  TASSIGN(v100, v101);
  pipe_barrier(PIPE_V);
  TADDS(v100, v98, v5);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v102 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
  uint64_t v103 = (uint64_t) v25;
  TASSIGN(v102, v103);
  pipe_barrier(PIPE_V);
  TSQRT(v102, v100);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v16);
  uint64_t v105 = (uint64_t) v17;
  TASSIGN(v104, v105);
  pipe_barrier(PIPE_V);
  TRECIP(v104, v102);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 1, 16> v106 = pto::Shape<1, 1, 1, 1, 16>();
  pto::Stride<16, 16, 16, 16, 1> v107 = pto::Stride<16, 16, 16, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v108 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v2 + (v4 + v4 * (unsigned) v16 + v4 * (unsigned) v14), v106, v107);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v108, v104);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_mixed_flat_inline127__ssa_v0
    __gm__ Tensor* x_mixed_flat_inline127__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* x_mixed_flat_inline127__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(x_mixed_flat_inline127__ssa_v0_tensor->buffer.addr) + x_mixed_flat_inline127__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Forward to ptoas-generated function
    ffn_norm_rms(x_mixed_flat_inline127__ssa_v0, ret0__out);
}
