// Kernel Function: gate_dot_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void gate_dot_0(__gm__ float* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, __gm__ float* v4, __gm__ float* v5) {
  RoundMode v6 = RoundMode::CAST_ROUND;
  unsigned v7 = 0;
  const int32_t v8 = 480;
  const int32_t v9 = 15;
  const int32_t v10 = 448;
  const int32_t v11 = 14;
  const int32_t v12 = 416;
  const int32_t v13 = 13;
  const int32_t v14 = 384;
  const int32_t v15 = 12;
  const int32_t v16 = 352;
  const int32_t v17 = 11;
  const int32_t v18 = 320;
  const int32_t v19 = 10;
  const int32_t v20 = 288;
  const int32_t v21 = 9;
  const int32_t v22 = 256;
  const int32_t v23 = 224;
  const int32_t v24 = 7;
  const int32_t v25 = 192;
  const int32_t v26 = 6;
  const int32_t v27 = 160;
  const int32_t v28 = 5;
  const int32_t v29 = 128;
  const int32_t v30 = 4;
  const int32_t v31 = 96;
  const int32_t v32 = 3;
  const int32_t v33 = 64;
  const int32_t v34 = 2;
  const int32_t v35 = 32;
  const float v36 = 1.0f;
  const float v37 = 0.0f;
  const int32_t v38 = 0;
  const int32_t v39 = 512;
  const int32_t v40 = 8;
  const int32_t v41 = 4096;
  const int32_t v42 = 16;
  const int32_t v43 = 1;
  const int64_t v44 = 32896;
  const int64_t v45 = 32832;
  const int64_t v46 = 32768;
  const int64_t v47 = 0;
  const int64_t v48 = 82176;
  const int64_t v49 = 49408;
  const int64_t v50 = 33024;
  const int64_t v51 = 32960;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v52 = (size_t) v43;
  size_t v53 = (size_t) v40;
  size_t v54 = (size_t) v38;
  set_flag(PIPE_S, PIPE_V, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  for (size_t v55 = v54; v55 < v53; v55 += v52) {
    int32_t v56 = (int32_t) v55;
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v58 = (uint64_t) v51;
    TASSIGN(v57, v58);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
    TEXPANDS(v57, v37);
    for (size_t v59 = v54; v59 < v53; v59 += v52) {
      int32_t v60 = (int32_t) ((uint32_t) ((int32_t) v59) * (uint32_t) v39);
      Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v61 = Tile<TileType::Vec, bfloat16_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v42, v39);
      uint64_t v62 = (uint64_t) v50;
      TASSIGN(v61, v62);
      pto::Shape<1, 1, 1, 16, 512> v63 = pto::Shape<1, 1, 1, 16, 512>();
      pto::Stride<65536, 65536, 65536, 4096, 1> v64 = pto::Stride<65536, 65536, 65536, 4096, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v65 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v7 + v7 * (unsigned) v41 + (unsigned) v60 * (unsigned) v43), v63, v64);
      wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      TLOAD(v61, v65);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v42, v39);
      uint64_t v67 = (uint64_t) v49;
      TASSIGN(v66, v67);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
      TCVT(v66, v61, v6);
      set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v39);
      uint64_t v69 = (uint64_t) v48;
      TASSIGN(v68, v69);
      pto::Shape<1, 1, 1, 1, 512> v70 = pto::Shape<1, 1, 1, 1, 512>();
      pto::Stride<4096, 4096, 4096, 4096, 1> v71 = pto::Stride<4096, 4096, 4096, 4096, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v72 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v3 + (v7 + (unsigned) v56 * (unsigned) v41 + (unsigned) v60 * (unsigned) v43), v70, v71);
      wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
      TLOAD(v68, v72);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v42, v39);
      uint64_t v74 = (uint64_t) v49;
      TASSIGN(v73, v74);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
      pipe_barrier(PIPE_V);
      TCOLEXPANDMUL(v73, v66, v68);
      set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v42, v39);
      uint64_t v76 = (uint64_t) v47;
      TASSIGN(v75, v76);
      Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v77 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v42, v43);
      uint64_t v78 = (uint64_t) v46;
      TASSIGN(v77, v78);
      pipe_barrier(PIPE_V);
      TROWSUM(v77, v73, v75);
      Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v79 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
      uint64_t v80 = (uint64_t) v46;
      TASSIGN(v79, v80);
      Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v81 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
      uint64_t v82 = (uint64_t) v51;
      TASSIGN(v81, v82);
      pipe_barrier(PIPE_V);
      TADD(v81, v57, v79);
    };
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pto::Shape<1, 1, 1, 1, 16> v83 = pto::Shape<1, 1, 1, 1, 16>();
    pto::Stride<16, 16, 16, 16, 1> v84 = pto::Stride<16, 16, 16, 16, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v85 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v1 + (v7 + v7 * (unsigned) v42 + v7 * (unsigned) v43), v83, v84);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v85, v57);
    set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    float v86 = v4[v55];
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v87 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v88 = (uint64_t) v51;
    TASSIGN(v87, v88);
    wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
    TLOAD(v87, v85);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v89 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v90 = (uint64_t) v45;
    TASSIGN(v89, v90);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    TMULS(v89, v87, v37);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v91 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v92 = (uint64_t) v45;
    TASSIGN(v91, v92);
    pipe_barrier(PIPE_V);
    TMAX(v91, v87, v89);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v93 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v94 = (uint64_t) v44;
    TASSIGN(v93, v94);
    TNEG(v93, v87);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v95 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v96 = (uint64_t) v51;
    TASSIGN(v95, v96);
    pipe_barrier(PIPE_V);
    TMAX(v95, v87, v93);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v97 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v98 = (uint64_t) v51;
    TASSIGN(v97, v98);
    pipe_barrier(PIPE_V);
    TNEG(v97, v95);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v99 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v100 = (uint64_t) v51;
    TASSIGN(v99, v100);
    pipe_barrier(PIPE_V);
    TEXP(v99, v97);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v101 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v102 = (uint64_t) v51;
    TASSIGN(v101, v102);
    pipe_barrier(PIPE_V);
    TADDS(v101, v99, v36);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v103 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v104 = (uint64_t) v51;
    TASSIGN(v103, v104);
    pipe_barrier(PIPE_V);
    TLOG(v103, v101);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v105 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v106 = (uint64_t) v51;
    TASSIGN(v105, v106);
    pipe_barrier(PIPE_V);
    TADD(v105, v91, v103);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v107 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v108 = (uint64_t) v51;
    TASSIGN(v107, v108);
    pipe_barrier(PIPE_V);
    TSQRT(v107, v105);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v109 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v110 = (uint64_t) v51;
    TASSIGN(v109, v110);
    pipe_barrier(PIPE_V);
    TADDS(v109, v107, v86);
    set_flag(PIPE_V, PIPE_S, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v111 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v43, v42);
    uint64_t v112 = (uint64_t) v51;
    TASSIGN(v111, v112);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
    float v113 = v111.GetValue(v38);
    v5[v55] = v113;
    float v114 = v111.GetValue(v43);
    int32_t v115 = (int32_t) ((uint32_t) v56 + (uint32_t) v35);
    v5[v115] = v114;
    float v116 = v111.GetValue(v34);
    int32_t v117 = (int32_t) ((uint32_t) v56 + (uint32_t) v33);
    v5[v117] = v116;
    float v118 = v111.GetValue(v32);
    int32_t v119 = (int32_t) ((uint32_t) v56 + (uint32_t) v31);
    v5[v119] = v118;
    float v120 = v111.GetValue(v30);
    int32_t v121 = (int32_t) ((uint32_t) v56 + (uint32_t) v29);
    v5[v121] = v120;
    float v122 = v111.GetValue(v28);
    int32_t v123 = (int32_t) ((uint32_t) v56 + (uint32_t) v27);
    v5[v123] = v122;
    float v124 = v111.GetValue(v26);
    int32_t v125 = (int32_t) ((uint32_t) v56 + (uint32_t) v25);
    v5[v125] = v124;
    float v126 = v111.GetValue(v24);
    int32_t v127 = (int32_t) ((uint32_t) v56 + (uint32_t) v23);
    v5[v127] = v126;
    float v128 = v111.GetValue(v40);
    int32_t v129 = (int32_t) ((uint32_t) v56 + (uint32_t) v22);
    v5[v129] = v128;
    float v130 = v111.GetValue(v21);
    int32_t v131 = (int32_t) ((uint32_t) v56 + (uint32_t) v20);
    v5[v131] = v130;
    float v132 = v111.GetValue(v19);
    int32_t v133 = (int32_t) ((uint32_t) v56 + (uint32_t) v18);
    v5[v133] = v132;
    float v134 = v111.GetValue(v17);
    int32_t v135 = (int32_t) ((uint32_t) v56 + (uint32_t) v16);
    v5[v135] = v134;
    float v136 = v111.GetValue(v15);
    int32_t v137 = (int32_t) ((uint32_t) v56 + (uint32_t) v14);
    v5[v137] = v136;
    float v138 = v111.GetValue(v13);
    int32_t v139 = (int32_t) ((uint32_t) v56 + (uint32_t) v12);
    v5[v139] = v138;
    float v140 = v111.GetValue(v11);
    int32_t v141 = (int32_t) ((uint32_t) v56 + (uint32_t) v10);
    v5[v141] = v140;
    float v142 = v111.GetValue(v9);
    set_flag(PIPE_S, PIPE_V, EVENT_ID0);
    int32_t v143 = (int32_t) ((uint32_t) v56 + (uint32_t) v8);
    v5[v143] = v142;
  }
  wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: score_acc_buf_inline117__ssa_v0
    __gm__ Tensor* score_acc_buf_inline117__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* score_acc_buf_inline117__ssa_v0 = reinterpret_cast<__gm__ float*>(score_acc_buf_inline117__ssa_v0_tensor->buffer.addr) + score_acc_buf_inline117__ssa_v0_tensor->start_offset;

    // Unpack tensor: x_norm_bf16_inline111__rv_v2
    __gm__ Tensor* x_norm_bf16_inline111__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* x_norm_bf16_inline111__rv_v2 = reinterpret_cast<__gm__ bfloat16_t*>(x_norm_bf16_inline111__rv_v2_tensor->buffer.addr) + x_norm_bf16_inline111__rv_v2_tensor->start_offset;

    // Unpack tensor: gate_w__ssa_v0
    __gm__ Tensor* gate_w__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* gate_w__ssa_v0 = reinterpret_cast<__gm__ float*>(gate_w__ssa_v0_tensor->buffer.addr) + gate_w__ssa_v0_tensor->start_offset;

    // Unpack tensor: gate_bias__ssa_v0
    __gm__ Tensor* gate_bias__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* gate_bias__ssa_v0 = reinterpret_cast<__gm__ float*>(gate_bias__ssa_v0_tensor->buffer.addr) + gate_bias__ssa_v0_tensor->start_offset;

    // Unpack tensor: biased_flat_inline133__ssa_v0
    __gm__ Tensor* biased_flat_inline133__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* biased_flat_inline133__ssa_v0 = reinterpret_cast<__gm__ float*>(biased_flat_inline133__ssa_v0_tensor->buffer.addr) + biased_flat_inline133__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    gate_dot_0(score_acc_buf_inline117__ssa_v0, x_norm_bf16_inline111__rv_v2, gate_w__ssa_v0, gate_bias__ssa_v0, biased_flat_inline133__ssa_v0);
}
