// Kernel Function: hc_post
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void hc_post(__gm__ bfloat16_t* v1, __gm__ float* v2, __gm__ bfloat16_t* v3, __gm__ float* v4, __gm__ bfloat16_t* v5, int32_t v6, int32_t v7) {
  RoundMode v8 = RoundMode::CAST_ROUND;
  unsigned v9 = 0;
  const int32_t v10 = 512;
  const int32_t v11 = 8;
  const int32_t v12 = 4;
  const int32_t v13 = 0;
  const int32_t v14 = 4096;
  const int32_t v15 = 1;
  const int32_t v16 = 16384;
  const int32_t v17 = 16;
  const int64_t v18 = 3072;
  const int64_t v19 = 1024;
  const int64_t v20 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v21 = (size_t) v15;
  size_t v22 = (size_t) v13;
  set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  for (size_t v23 = v22; v23 < ((size_t) v17); v23 += v21) {
    int32_t v24 = (int32_t) ((uint32_t) ((int32_t) (uint32_t) v6 * (uint32_t) v17) + (uint32_t) ((int32_t) v23));
    __gm__ bfloat16_t* v25;
    if (v24 < v17) {
      float v26 = v2[(int32_t) ((uint32_t) ((int32_t) (uint32_t) v24 * (uint32_t) v12) + (uint32_t) v7)];
      for (size_t v27 = v22; v27 < ((size_t) v11); v27 += v21) {
        int32_t v28 = (int32_t) ((uint32_t) ((int32_t) v27) * (uint32_t) v10);
        Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
        uint64_t v30 = (uint64_t) v20;
        TASSIGN(v29, v30);
        pto::Shape<1, 1, 1, 1, 512> v31 = pto::Shape<1, 1, 1, 1, 512>();
        pto::Stride<4096, 4096, 4096, 4096, 1> v32 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v33 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v3 + (v9 + (unsigned) v24 * (unsigned) v14 + (unsigned) v28 * (unsigned) v15), v31, v32);
        wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
        TLOAD(v29, v33);
        set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
        uint64_t v35 = (uint64_t) v19;
        TASSIGN(v34, v35);
        wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
        TCVT(v34, v29, v8);
        set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
        uint64_t v37 = (uint64_t) v19;
        TASSIGN(v36, v37);
        pipe_barrier(PIPE_V);
        TMULS(v36, v34, v26);
        wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        for (size_t v38 = v22; v38 < ((size_t) v12); v38 += v21) {
          int32_t v39 = (int32_t) v38;
          float v40 = v4[(int32_t) ((uint32_t) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v24 * (uint32_t) v17) + (uint32_t) ((int32_t) (uint32_t) v39 * (uint32_t) v12)) + (uint32_t) v7)];
          Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
          uint64_t v42 = (uint64_t) v20;
          TASSIGN(v41, v42);
          pto::Shape<1, 1, 1, 1, 512> v43 = pto::Shape<1, 1, 1, 1, 512>();
          pto::Stride<16384, 16384, 16384, 16384, 1> v44 = pto::Stride<16384, 16384, 16384, 16384, 1>();
          GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND> v45 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(v5 + (v9 + (unsigned) v24 * (unsigned) v16 + (unsigned) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v39 * (uint32_t) v14) + (uint32_t) v28) * (unsigned) v15), v43, v44);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
          TLOAD(v41, v45);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v46 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
          uint64_t v47 = (uint64_t) v18;
          TASSIGN(v46, v47);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
          pipe_barrier(PIPE_V);
          TCVT(v46, v41, v8);
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
          uint64_t v49 = (uint64_t) v18;
          TASSIGN(v48, v49);
          pipe_barrier(PIPE_V);
          TMULS(v48, v46, v40);
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
          uint64_t v51 = (uint64_t) v19;
          TASSIGN(v50, v51);
          pipe_barrier(PIPE_V);
          TADD(v50, v36, v48);
        };
        Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v10);
        uint64_t v53 = (uint64_t) v20;
        TASSIGN(v52, v53);
        pipe_barrier(PIPE_V);
        TCVT(v52, v36, v8);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        pto::Shape<1, 1, 1, 1, 512> v54 = pto::Shape<1, 1, 1, 1, 512>();
        pto::Stride<16384, 16384, 16384, 16384, 1> v55 = pto::Stride<16384, 16384, 16384, 16384, 1>();
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND> v56 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(v1 + (v9 + (unsigned) v24 * (unsigned) v16 + (unsigned) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v7 * (uint32_t) v14) + (uint32_t) v28) * (unsigned) v15), v54, v55);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        TSTORE(v56, v52);
        set_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
      };
      v25 = v1;
    } else {
      v25 = v1;
    };
  }
  wait_flag(PIPE_MTE3, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: y_flat_inline7__co_l0_iter_v3
    __gm__ Tensor* y_flat_inline7__co_l0_iter_v3_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* y_flat_inline7__co_l0_iter_v3 = reinterpret_cast<__gm__ bfloat16_t*>(y_flat_inline7__co_l0_iter_v3_tensor->buffer.addr) + y_flat_inline7__co_l0_iter_v3_tensor->start_offset;

    // Unpack tensor: post_flat_inline8__ssa_v0
    __gm__ Tensor* post_flat_inline8__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* post_flat_inline8__ssa_v0 = reinterpret_cast<__gm__ float*>(post_flat_inline8__ssa_v0_tensor->buffer.addr) + post_flat_inline8__ssa_v0_tensor->start_offset;

    // Unpack tensor: x_flat_inline2__ssa_v0
    __gm__ Tensor* x_flat_inline2__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ bfloat16_t* x_flat_inline2__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(x_flat_inline2__ssa_v0_tensor->buffer.addr) + x_flat_inline2__ssa_v0_tensor->start_offset;

    // Unpack tensor: comb_flat_inline9__ssa_v0
    __gm__ Tensor* comb_flat_inline9__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* comb_flat_inline9__ssa_v0 = reinterpret_cast<__gm__ float*>(comb_flat_inline9__ssa_v0_tensor->buffer.addr) + comb_flat_inline9__ssa_v0_tensor->start_offset;

    // Unpack tensor: residual_flat_inline6__ssa_v0
    __gm__ Tensor* residual_flat_inline6__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ bfloat16_t* residual_flat_inline6__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(residual_flat_inline6__ssa_v0_tensor->buffer.addr) + residual_flat_inline6__ssa_v0_tensor->start_offset;

    // Unpack scalar: t_inline10__co_idx_v0
    union { uint64_t u64; int64_t val; } t_inline10__co_idx_v0_conv;
    t_inline10__co_idx_v0_conv.u64 = args[5];
    int64_t t_inline10__co_idx_v0 = t_inline10__co_idx_v0_conv.val;

    // Unpack scalar: out_h_inline3__idx_v0
    union { uint64_t u64; int64_t val; } out_h_inline3__idx_v0_conv;
    out_h_inline3__idx_v0_conv.u64 = args[6];
    int64_t out_h_inline3__idx_v0 = out_h_inline3__idx_v0_conv.val;

    // Forward to ptoas-generated function
    hc_post(y_flat_inline7__co_l0_iter_v3, post_flat_inline8__ssa_v0, x_flat_inline2__ssa_v0, comb_flat_inline9__ssa_v0, residual_flat_inline6__ssa_v0, t_inline10__co_idx_v0, out_h_inline3__idx_v0);
}
