// Kernel Function: linear
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void linear(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4) {
  unsigned v5 = 0;
  const int32_t v6 = 480;
  const int32_t v7 = 15;
  const int32_t v8 = 448;
  const int32_t v9 = 14;
  const int32_t v10 = 416;
  const int32_t v11 = 13;
  const int32_t v12 = 384;
  const int32_t v13 = 12;
  const int32_t v14 = 352;
  const int32_t v15 = 11;
  const int32_t v16 = 320;
  const int32_t v17 = 10;
  const int32_t v18 = 288;
  const int32_t v19 = 9;
  const int32_t v20 = 256;
  const int32_t v21 = 8;
  const int32_t v22 = 224;
  const int32_t v23 = 7;
  const int32_t v24 = 192;
  const int32_t v25 = 6;
  const int32_t v26 = 160;
  const int32_t v27 = 5;
  const int32_t v28 = 128;
  const int32_t v29 = 4;
  const int32_t v30 = 96;
  const int32_t v31 = 3;
  const int32_t v32 = 64;
  const int32_t v33 = 2;
  const int32_t v34 = 32;
  const float v35 = 0.0f;
  const int32_t v36 = 0;
  const int32_t v37 = 512;
  const int32_t v38 = 24;
  const int32_t v39 = 1;
  const int32_t v40 = 16384;
  const int32_t v41 = 16;
  const int64_t v42 = 0;
  const int64_t v43 = 35008;
  const int64_t v44 = 32960;
  const int64_t v45 = 192;
  const int64_t v46 = 128;
  const int64_t v47 = 64;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v48 = (size_t) v39;
  size_t v49 = (size_t) v36;
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
  uint64_t v51 = (uint64_t) v47;
  TASSIGN(v50, v51);
  pto::Shape<1, 1, 1, 1, 16> v52 = pto::Shape<1, 1, 1, 1, 16>();
  pto::Stride<16, 16, 16, 16, 1> v53 = pto::Stride<16, 16, 16, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v54 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v3 + (v5 + v5 * (unsigned) v41 + v5 * (unsigned) v39), v52, v53);
  set_flag(PIPE_S, PIPE_V, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  TLOAD(v50, v54);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  for (size_t v55 = v49; v55 < ((size_t) v38); v55 += v48) {
    int32_t v56 = (int32_t) v55;
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
    uint64_t v58 = (uint64_t) v46;
    TASSIGN(v57, v58);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
    TEXPANDS(v57, v35);
    for (size_t v59 = v49; v59 < ((size_t) v34); v59 += v48) {
      int32_t v60 = (int32_t) ((uint32_t) ((int32_t) v59) * (uint32_t) v37);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v61 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v41, v37);
      uint64_t v62 = (uint64_t) v45;
      TASSIGN(v61, v62);
      pto::Shape<1, 1, 1, 16, 512> v63 = pto::Shape<1, 1, 1, 16, 512>();
      pto::Stride<262144, 262144, 262144, 16384, 1> v64 = pto::Stride<262144, 262144, 262144, 16384, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND> v65 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v40 + (unsigned) v60 * (unsigned) v39), v63, v64);
      wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      TLOAD(v61, v65);
      Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v37);
      uint64_t v67 = (uint64_t) v44;
      TASSIGN(v66, v67);
      pto::Shape<1, 1, 1, 1, 512> v68 = pto::Shape<1, 1, 1, 1, 512>();
      pto::Stride<16384, 16384, 16384, 16384, 1> v69 = pto::Stride<16384, 16384, 16384, 16384, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND> v70 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(v2 + (v5 + (unsigned) v56 * (unsigned) v40 + (unsigned) v60 * (unsigned) v39), v68, v69);
      TLOAD(v66, v70);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v41, v37);
      uint64_t v72 = (uint64_t) v45;
      TASSIGN(v71, v72);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
      TCOLEXPANDMUL(v71, v61, v66);
      Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v41, v37);
      uint64_t v74 = (uint64_t) v43;
      TASSIGN(v73, v74);
      Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v41, v39);
      uint64_t v76 = (uint64_t) v42;
      TASSIGN(v75, v76);
      pipe_barrier(PIPE_V);
      TROWSUM(v75, v71, v73);
      set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v77 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
      uint64_t v78 = (uint64_t) v42;
      TASSIGN(v77, v78);
      Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v79 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
      uint64_t v80 = (uint64_t) v46;
      TASSIGN(v79, v80);
      pipe_barrier(PIPE_V);
      TADD(v79, v57, v77);
    };
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v81 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
    uint64_t v82 = (uint64_t) v46;
    TASSIGN(v81, v82);
    pipe_barrier(PIPE_V);
    TMUL(v81, v57, v50);
    set_flag(PIPE_V, PIPE_S, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v83 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v39, v41);
    uint64_t v84 = (uint64_t) v46;
    TASSIGN(v83, v84);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
    float v85 = v83.GetValue(v36);
    v4[v55] = v85;
    float v86 = v83.GetValue(v39);
    int32_t v87 = (int32_t) ((uint32_t) v56 + (uint32_t) v34);
    v4[v87] = v86;
    float v88 = v83.GetValue(v33);
    int32_t v89 = (int32_t) ((uint32_t) v56 + (uint32_t) v32);
    v4[v89] = v88;
    float v90 = v83.GetValue(v31);
    int32_t v91 = (int32_t) ((uint32_t) v56 + (uint32_t) v30);
    v4[v91] = v90;
    float v92 = v83.GetValue(v29);
    int32_t v93 = (int32_t) ((uint32_t) v56 + (uint32_t) v28);
    v4[v93] = v92;
    float v94 = v83.GetValue(v27);
    int32_t v95 = (int32_t) ((uint32_t) v56 + (uint32_t) v26);
    v4[v95] = v94;
    float v96 = v83.GetValue(v25);
    int32_t v97 = (int32_t) ((uint32_t) v56 + (uint32_t) v24);
    v4[v97] = v96;
    float v98 = v83.GetValue(v23);
    int32_t v99 = (int32_t) ((uint32_t) v56 + (uint32_t) v22);
    v4[v99] = v98;
    float v100 = v83.GetValue(v21);
    int32_t v101 = (int32_t) ((uint32_t) v56 + (uint32_t) v20);
    v4[v101] = v100;
    float v102 = v83.GetValue(v19);
    int32_t v103 = (int32_t) ((uint32_t) v56 + (uint32_t) v18);
    v4[v103] = v102;
    float v104 = v83.GetValue(v17);
    int32_t v105 = (int32_t) ((uint32_t) v56 + (uint32_t) v16);
    v4[v105] = v104;
    float v106 = v83.GetValue(v15);
    int32_t v107 = (int32_t) ((uint32_t) v56 + (uint32_t) v14);
    v4[v107] = v106;
    float v108 = v83.GetValue(v13);
    int32_t v109 = (int32_t) ((uint32_t) v56 + (uint32_t) v12);
    v4[v109] = v108;
    float v110 = v83.GetValue(v11);
    int32_t v111 = (int32_t) ((uint32_t) v56 + (uint32_t) v10);
    v4[v111] = v110;
    float v112 = v83.GetValue(v9);
    int32_t v113 = (int32_t) ((uint32_t) v56 + (uint32_t) v8);
    v4[v113] = v112;
    float v114 = v83.GetValue(v7);
    set_flag(PIPE_S, PIPE_V, EVENT_ID0);
    int32_t v115 = (int32_t) ((uint32_t) v56 + (uint32_t) v6);
    v4[v115] = v114;
  }
  wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_flat_fp32_inline49__rv_v2
    __gm__ Tensor* x_flat_fp32_inline49__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* x_flat_fp32_inline49__rv_v2 = reinterpret_cast<__gm__ float*>(x_flat_fp32_inline49__rv_v2_tensor->buffer.addr) + x_flat_fp32_inline49__rv_v2_tensor->start_offset;

    // Unpack tensor: hc_ffn_fn__ssa_v0
    __gm__ Tensor* hc_ffn_fn__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* hc_ffn_fn__ssa_v0 = reinterpret_cast<__gm__ float*>(hc_ffn_fn__ssa_v0_tensor->buffer.addr) + hc_ffn_fn__ssa_v0_tensor->start_offset;

    // Unpack tensor: inv_rms_inline75__ssa_v1
    __gm__ Tensor* inv_rms_inline75__ssa_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* inv_rms_inline75__ssa_v1 = reinterpret_cast<__gm__ float*>(inv_rms_inline75__ssa_v1_tensor->buffer.addr) + inv_rms_inline75__ssa_v1_tensor->start_offset;

    // Unpack tensor: mixes_flat_inline45__ssa_v0
    __gm__ Tensor* mixes_flat_inline45__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* mixes_flat_inline45__ssa_v0 = reinterpret_cast<__gm__ float*>(mixes_flat_inline45__ssa_v0_tensor->buffer.addr) + mixes_flat_inline45__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    linear(x_flat_fp32_inline49__rv_v2, hc_ffn_fn__ssa_v0, inv_rms_inline75__ssa_v1, mixes_flat_inline45__ssa_v0);
}
