// Kernel Function: mix_x
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void mix_x(__gm__ bfloat16_t* v1, __gm__ float* v2, __gm__ float* v3, int32_t v4) {
  RoundMode v5 = RoundMode::CAST_RINT;
  unsigned v6 = 0;
  const int32_t v7 = 4;
  const float v8 = 0.0f;
  const int32_t v9 = 512;
  const int32_t v10 = 8;
  const int32_t v11 = 0;
  const int32_t v12 = 16384;
  const int32_t v13 = 1;
  const int32_t v14 = 4096;
  const int32_t v15 = 16;
  const int64_t v16 = 4096;
  const int64_t v17 = 2048;
  const int64_t v18 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v19 = (size_t) v13;
  size_t v20 = (size_t) v11;
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  for (size_t v21 = v20; v21 < ((size_t) v15); v21 += v19) {
    int32_t v22 = (int32_t) ((uint32_t) ((int32_t) (uint32_t) v4 * (uint32_t) v15) + (uint32_t) ((int32_t) v21));
    __gm__ bfloat16_t* v23;
    if (v22 < v15) {
      for (size_t v24 = v20; v24 < ((size_t) v10); v24 += v19) {
        int32_t v25 = (int32_t) ((uint32_t) ((int32_t) v24) * (uint32_t) v9);
        Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v9);
        uint64_t v27 = (uint64_t) v18;
        TASSIGN(v26, v27);
        pipe_barrier(PIPE_V);
        TEXPANDS(v26, v8);
        for (size_t v28 = v20; v28 < ((size_t) v7); v28 += v19) {
          int32_t v29 = (int32_t) v28;
          float v30 = v2[(int32_t) ((uint32_t) ((int32_t) (uint32_t) v22 * (uint32_t) v10) + (uint32_t) v29)];
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v9);
          uint64_t v32 = (uint64_t) v17;
          TASSIGN(v31, v32);
          pto::Shape<1, 1, 1, 1, 512> v33 = pto::Shape<1, 1, 1, 1, 512>();
          pto::Stride<16384, 16384, 16384, 16384, 1> v34 = pto::Stride<16384, 16384, 16384, 16384, 1>();
          GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND> v35 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<16384, 16384, 16384, 16384, 1>, pto::Layout::ND>(v3 + (v6 + (unsigned) v22 * (unsigned) v12 + (unsigned) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v29 * (uint32_t) v14) + (uint32_t) v25) * (unsigned) v13), v33, v34);
          wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
          TLOAD(v31, v35);
          set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v9);
          uint64_t v37 = (uint64_t) v17;
          TASSIGN(v36, v37);
          wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
          TMULS(v36, v31, v30);
          Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v9);
          uint64_t v39 = (uint64_t) v18;
          TASSIGN(v38, v39);
          pipe_barrier(PIPE_V);
          TADD(v38, v26, v36);
          set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
        };
        Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v40 = Tile<TileType::Vec, bfloat16_t, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v9);
        uint64_t v41 = (uint64_t) v16;
        TASSIGN(v40, v41);
        pipe_barrier(PIPE_V);
        wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
        TCVT(v40, v26, v5);
        set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        pto::Shape<1, 1, 1, 1, 512> v42 = pto::Shape<1, 1, 1, 1, 512>();
        pto::Stride<4096, 4096, 4096, 4096, 1> v43 = pto::Stride<4096, 4096, 4096, 4096, 1>();
        GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND> v44 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<4096, 4096, 4096, 4096, 1>, pto::Layout::ND>(v1 + (v6 + (unsigned) v22 * (unsigned) v14 + (unsigned) v25 * (unsigned) v13), v42, v43);
        wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
        TSTORE(v44, v40);
        set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
      };
      v23 = v1;
    } else {
      v23 = v1;
    };
  }
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_mixed_view_inline55__co_l0_iter_v1
    __gm__ Tensor* x_mixed_view_inline55__co_l0_iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* x_mixed_view_inline55__co_l0_iter_v1 = reinterpret_cast<__gm__ bfloat16_t*>(x_mixed_view_inline55__co_l0_iter_v1_tensor->buffer.addr) + x_mixed_view_inline55__co_l0_iter_v1_tensor->start_offset;

    // Unpack tensor: pre_val_flat_inline44__ssa_v0
    __gm__ Tensor* pre_val_flat_inline44__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* pre_val_flat_inline44__ssa_v0 = reinterpret_cast<__gm__ float*>(pre_val_flat_inline44__ssa_v0_tensor->buffer.addr) + pre_val_flat_inline44__ssa_v0_tensor->start_offset;

    // Unpack tensor: x_flat_fp32_inline49__rv_v2
    __gm__ Tensor* x_flat_fp32_inline49__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* x_flat_fp32_inline49__rv_v2 = reinterpret_cast<__gm__ float*>(x_flat_fp32_inline49__rv_v2_tensor->buffer.addr) + x_flat_fp32_inline49__rv_v2_tensor->start_offset;

    // Unpack scalar: t_inline5__co_idx_v0
    union { uint64_t u64; int64_t val; } t_inline5__co_idx_v0_conv;
    t_inline5__co_idx_v0_conv.u64 = args[3];
    int64_t t_inline5__co_idx_v0 = t_inline5__co_idx_v0_conv.val;

    // Forward to ptoas-generated function
    mix_x(x_mixed_view_inline55__co_l0_iter_v1, pre_val_flat_inline44__ssa_v0, x_flat_fp32_inline49__rv_v2, t_inline5__co_idx_v0);
}
