// Kernel Function: recv_x_q
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void recv_x_q(__gm__ bfloat16_t* v1, __gm__ int8_t* v2, __gm__ float* v3, int32_t v4, int32_t v5) {
  RoundMode v6 = RoundMode::CAST_TRUNC;
  RoundMode v7 = RoundMode::CAST_ROUND;
  unsigned v8 = 0;
  const int32_t v9 = 131072;
  const float v10 = 127.0f;
  const int32_t v11 = 256;
  const int32_t v12 = 0;
  const float v13 = 9.99999974E-5f;
  const int32_t v14 = 16;
  const int32_t v15 = 1;
  const int32_t v16 = 4096;
  const int64_t v17 = 24640;
  const int64_t v18 = 16448;
  const int64_t v19 = 64;
  const int64_t v20 = 0;
  const int64_t v21 = 69760;
  const int64_t v22 = 53376;
  const int64_t v23 = 36992;
  const int64_t v24 = 28800;
  const int64_t v25 = 28736;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v26 = (size_t) v16;
  size_t v27 = (size_t) v12;
  size_t v28 = (size_t) v11;
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v30 = (uint64_t) v25;
  TASSIGN(v29, v30);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  TEXPANDS(v29, v13);
  for (size_t v31 = v27; v31 < v26; v31 += v28) {
    Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v33 = (uint64_t) v24;
    TASSIGN(v32, v33);
    pto::Shape<1, 1, 1, 16, 256> v34 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<131072, 131072, 131072, 4096, 1> v35 = pto::Stride<131072, 131072, 131072, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND> v36 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>(v1 + ((v8 + (unsigned) v4 * (unsigned) v9) + (unsigned) v5 * (unsigned) v16 + (unsigned) ((int32_t) v31) * (unsigned) v15), v34, v35);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v32, v36);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v38 = (uint64_t) v23;
    TASSIGN(v37, v38);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v37, v32, v7);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v40 = (uint64_t) v23;
    TASSIGN(v39, v40);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v42 = (uint64_t) v22;
    TASSIGN(v41, v42);
    pipe_barrier(PIPE_V);
    TNEG(v41, v39);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v44 = (uint64_t) v23;
    TASSIGN(v43, v44);
    pipe_barrier(PIPE_V);
    TMAX(v43, v39, v41);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v46 = (uint64_t) v22;
    TASSIGN(v45, v46);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v15);
    uint64_t v48 = (uint64_t) v21;
    TASSIGN(v47, v48);
    pipe_barrier(PIPE_V);
    TROWMAX(v47, v43, v45);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
    uint64_t v50 = (uint64_t) v21;
    TASSIGN(v49, v50);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v51 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
    uint64_t v52 = (uint64_t) v25;
    TASSIGN(v51, v52);
    pipe_barrier(PIPE_V);
    TMAX(v51, v29, v49);
  }
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v53 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v54 = (uint64_t) v20;
  TASSIGN(v53, v54);
  TEXPANDS(v53, v10);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v55 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v56 = (uint64_t) v25;
  TASSIGN(v55, v56);
  pipe_barrier(PIPE_V);
  TDIV(v55, v53, v29);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v57 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v14);
  uint64_t v58 = (uint64_t) v20;
  TASSIGN(v57, v58);
  pipe_barrier(PIPE_V);
  TRECIP(v57, v55);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v59 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v15);
  uint64_t v60 = (uint64_t) v20;
  TASSIGN(v59, v60);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v61 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v15);
  uint64_t v62 = (uint64_t) v25;
  TASSIGN(v61, v62);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  for (size_t v63 = v27; v63 < v26; v63 += v28) {
    int32_t v64 = (int32_t) v63;
    Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v66 = (uint64_t) v24;
    TASSIGN(v65, v66);
    pto::Shape<1, 1, 1, 16, 256> v67 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<131072, 131072, 131072, 4096, 1> v68 = pto::Stride<131072, 131072, 131072, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND> v69 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<131072, 131072, 131072, 4096, 1>, pto::Layout::ND>(v1 + ((v8 + (unsigned) v4 * (unsigned) v9) + (unsigned) v5 * (unsigned) v16 + (unsigned) v64 * (unsigned) v15), v67, v68);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v65, v69);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v71 = (uint64_t) v23;
    TASSIGN(v70, v71);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TCVT(v70, v65, v7);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v73 = (uint64_t) v23;
    TASSIGN(v72, v73);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v75 = (uint64_t) v23;
    TASSIGN(v74, v75);
    pipe_barrier(PIPE_V);
    TROWEXPANDMUL(v74, v72, v61);
    Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v77 = (uint64_t) v19;
    TASSIGN(v76, v77);
    pipe_barrier(PIPE_V);
    TCVT(v76, v74, v7);
    Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v78 = Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v79 = (uint64_t) v18;
    TASSIGN(v78, v79);
    pipe_barrier(PIPE_V);
    TCVT(v78, v76, v7);
    Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v81 = (uint64_t) v17;
    TASSIGN(v80, v81);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TCVT(v80, v78, v6);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pto::Shape<1, 1, 1, 16, 256> v82 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v83 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v84 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v8 + v8 * (unsigned) v16 + (unsigned) v64 * (unsigned) v15), v82, v83);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v84, v80);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  }
  pto::Shape<1, 1, 1, 16, 1> v85 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v86 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v87 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v8 + v8 * (unsigned) v15 + v8 * (unsigned) v14), v85, v86);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v87, v59);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: recv_x__ssa_v0
    __gm__ Tensor* recv_x__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* recv_x__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(recv_x__ssa_v0_tensor->buffer.addr) + recv_x__ssa_v0_tensor->start_offset;

    // Unpack tensor: recv_x_tile_i8_inline75__ssa_v0
    __gm__ Tensor* recv_x_tile_i8_inline75__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* recv_x_tile_i8_inline75__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(recv_x_tile_i8_inline75__ssa_v0_tensor->buffer.addr) + recv_x_tile_i8_inline75__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: local_i_inline67__idx_v0
    union { uint64_t u64; int64_t val; } local_i_inline67__idx_v0_conv;
    local_i_inline67__idx_v0_conv.u64 = args[3];
    int64_t local_i_inline67__idx_v0 = local_i_inline67__idx_v0_conv.val;

    // Unpack scalar: t0_inline47__ssa_v0
    union { uint64_t u64; int64_t val; } t0_inline47__ssa_v0_conv;
    t0_inline47__ssa_v0_conv.u64 = args[4];
    int64_t t0_inline47__ssa_v0 = t0_inline47__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    recv_x_q(recv_x__ssa_v0, recv_x_tile_i8_inline75__ssa_v0, ret0__out, local_i_inline67__idx_v0, t0_inline47__ssa_v0);
}
