// Kernel Function: rms
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void rms(__gm__ float* v1, __gm__ float* v2) {
  unsigned v3 = 0;
  const float v4 = 9.99999997E-7f;
  const float v5 = 6.10351563E-5f;
  const int32_t v6 = 1536;
  const int32_t v7 = 1024;
  const int32_t v8 = 512;
  const int32_t v9 = 4;
  const int32_t v10 = 32;
  const int32_t v11 = 0;
  const float v12 = 0.0f;
  const int32_t v13 = 1;
  const int32_t v14 = 16384;
  const int32_t v15 = 16;
  const int64_t v16 = 0;
  const int64_t v17 = 163968;
  const int64_t v18 = 131200;
  const int64_t v19 = 98432;
  const int64_t v20 = 65664;
  const int64_t v21 = 32896;
  const int64_t v22 = 128;
  const int64_t v23 = 64;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v24 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
  uint64_t v25 = (uint64_t) v23;
  TASSIGN(v24, v25);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  TEXPANDS(v24, v12);
  for (size_t v26 = (size_t) v11; v26 < ((size_t) v10); v26 += (size_t) v9) {
    int32_t v27 = (int32_t) ((uint32_t) ((int32_t) v26) * (uint32_t) v8);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v29 = (uint64_t) v22;
    TASSIGN(v28, v29);
    pto::Shape<1, 1, 1, 16, 512> v30 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<262144, 262144, 262144, 16384, 1> v31 = pto::Stride<262144, 262144, 262144, 16384, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND> v32 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND>(v1 + (v3 + v3 * (unsigned) v14 + (unsigned) v27 * (unsigned) v13), v30, v31);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v28, v32);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v34 = (uint64_t) v21;
    TASSIGN(v33, v34);
    pto::Shape<1, 1, 1, 16, 512> v35 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<262144, 262144, 262144, 16384, 1> v36 = pto::Stride<262144, 262144, 262144, 16384, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND>(v1 + (v3 + v3 * (unsigned) v14 + (unsigned) ((int32_t) (uint32_t) v27 + (uint32_t) v8) * (unsigned) v13), v35, v36);
    TLOAD(v33, v37);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v39 = (uint64_t) v20;
    TASSIGN(v38, v39);
    pto::Shape<1, 1, 1, 16, 512> v40 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<262144, 262144, 262144, 16384, 1> v41 = pto::Stride<262144, 262144, 262144, 16384, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND> v42 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND>(v1 + (v3 + v3 * (unsigned) v14 + (unsigned) ((int32_t) (uint32_t) v27 + (uint32_t) v7) * (unsigned) v13), v40, v41);
    TLOAD(v38, v42);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v44 = (uint64_t) v19;
    TASSIGN(v43, v44);
    pto::Shape<1, 1, 1, 16, 512> v45 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<262144, 262144, 262144, 16384, 1> v46 = pto::Stride<262144, 262144, 262144, 16384, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND> v47 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<262144, 262144, 262144, 16384, 1>, pto::Layout::ND>(v1 + (v3 + v3 * (unsigned) v14 + (unsigned) ((int32_t) (uint32_t) v27 + (uint32_t) v6) * (unsigned) v13), v45, v46);
    TLOAD(v43, v47);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v49 = (uint64_t) v22;
    TASSIGN(v48, v49);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TMUL(v48, v28, v28);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v51 = (uint64_t) v18;
    TASSIGN(v50, v51);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
    uint64_t v53 = (uint64_t) v17;
    TASSIGN(v52, v53);
    pipe_barrier(PIPE_V);
    TROWSUM(v52, v48, v50);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v55 = (uint64_t) v17;
    TASSIGN(v54, v55);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v57 = (uint64_t) v16;
    TASSIGN(v56, v57);
    pipe_barrier(PIPE_V);
    TADD(v56, v24, v54);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v59 = (uint64_t) v22;
    TASSIGN(v58, v59);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TMUL(v58, v33, v33);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v61 = (uint64_t) v21;
    TASSIGN(v60, v61);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
    uint64_t v63 = (uint64_t) v17;
    TASSIGN(v62, v63);
    pipe_barrier(PIPE_V);
    TROWSUM(v62, v58, v60);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v65 = (uint64_t) v17;
    TASSIGN(v64, v65);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v67 = (uint64_t) v16;
    TASSIGN(v66, v67);
    pipe_barrier(PIPE_V);
    TADD(v66, v56, v64);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v68 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v69 = (uint64_t) v22;
    TASSIGN(v68, v69);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
    TMUL(v68, v38, v38);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v70 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v71 = (uint64_t) v21;
    TASSIGN(v70, v71);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v72 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
    uint64_t v73 = (uint64_t) v17;
    TASSIGN(v72, v73);
    pipe_barrier(PIPE_V);
    TROWSUM(v72, v68, v70);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v75 = (uint64_t) v17;
    TASSIGN(v74, v75);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v77 = (uint64_t) v16;
    TASSIGN(v76, v77);
    pipe_barrier(PIPE_V);
    TADD(v76, v66, v74);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v78 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v79 = (uint64_t) v22;
    TASSIGN(v78, v79);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
    TMUL(v78, v43, v43);
    Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v8);
    uint64_t v81 = (uint64_t) v21;
    TASSIGN(v80, v81);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v82 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v15, v13);
    uint64_t v83 = (uint64_t) v17;
    TASSIGN(v82, v83);
    pipe_barrier(PIPE_V);
    TROWSUM(v82, v78, v80);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v85 = (uint64_t) v17;
    TASSIGN(v84, v85);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v86 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
    uint64_t v87 = (uint64_t) v23;
    TASSIGN(v86, v87);
    pipe_barrier(PIPE_V);
    TADD(v86, v76, v84);
  }
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v88 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
  uint64_t v89 = (uint64_t) v23;
  TASSIGN(v88, v89);
  pipe_barrier(PIPE_V);
  TMULS(v88, v24, v5);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v90 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
  uint64_t v91 = (uint64_t) v23;
  TASSIGN(v90, v91);
  pipe_barrier(PIPE_V);
  TADDS(v90, v88, v4);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v92 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
  uint64_t v93 = (uint64_t) v23;
  TASSIGN(v92, v93);
  pipe_barrier(PIPE_V);
  TSQRT(v92, v90);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v94 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v15);
  uint64_t v95 = (uint64_t) v16;
  TASSIGN(v94, v95);
  pipe_barrier(PIPE_V);
  TRECIP(v94, v92);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 1, 16> v96 = pto::Shape<1, 1, 1, 1, 16>();
  pto::Stride<16, 16, 16, 16, 1> v97 = pto::Stride<16, 16, 16, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v98 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v2 + (v3 + v3 * (unsigned) v15 + v3 * (unsigned) v13), v96, v97);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v98, v94);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_flat_fp32_inline49__rv_v2
    __gm__ Tensor* x_flat_fp32_inline49__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* x_flat_fp32_inline49__rv_v2 = reinterpret_cast<__gm__ float*>(x_flat_fp32_inline49__rv_v2_tensor->buffer.addr) + x_flat_fp32_inline49__rv_v2_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Forward to ptoas-generated function
    rms(x_flat_fp32_inline49__rv_v2, ret0__out);
}
