// Kernel Function: route_normalize_weights
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void route_normalize_weights(__gm__ float* v1, __gm__ float* v2) {
  unsigned v3 = 0;
  const float v4 = 1.0f;
  const int32_t v5 = 128;
  const int32_t v6 = 1;
  const int32_t v7 = 32;
  const int32_t v8 = 16;
  const int64_t v9 = 10240;
  const int64_t v10 = 2048;
  const int64_t v11 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v12 = Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v7);
  uint64_t v13 = (uint64_t) v11;
  TASSIGN(v12, v13);
  pto::Shape<1, 1, 1, 16, 32> v14 = pto::Shape<1, 1, 1, 16, 32>();
  pto::Stride<512, 512, 512, 32, 1> v15 = pto::Stride<512, 512, 512, 32, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v16 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(v1 + (v3 + v3 * (unsigned) v7 + v3 * (unsigned) v6), v14, v15);
  TLOAD(v12, v16);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v17 = Tile<TileType::Vec, float, 16, 128, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v5);
  uint64_t v18 = (uint64_t) v10;
  TASSIGN(v17, v18);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v19 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v6);
  uint64_t v20 = (uint64_t) v9;
  TASSIGN(v19, v20);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TROWSUM(v19, v12, v17);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v21 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v6);
  uint64_t v22 = (uint64_t) v9;
  TASSIGN(v21, v22);
  Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v7);
  uint64_t v24 = (uint64_t) v11;
  TASSIGN(v23, v24);
  pipe_barrier(PIPE_V);
  TROWEXPANDDIV(v23, v12, v21);
  Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Vec, float, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v8, v7);
  uint64_t v26 = (uint64_t) v11;
  TASSIGN(v25, v26);
  pipe_barrier(PIPE_V);
  TMULS(v25, v23, v4);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 32> v27 = pto::Shape<1, 1, 1, 16, 32>();
  pto::Stride<512, 512, 512, 32, 1> v28 = pto::Stride<512, 512, 512, 32, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v29 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(v2 + (v3 + v3 * (unsigned) v7 + v3 * (unsigned) v6), v27, v28);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v29, v25);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: topk_vals_pad_inline110__ssa_v17
    __gm__ Tensor* topk_vals_pad_inline110__ssa_v17_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* topk_vals_pad_inline110__ssa_v17 = reinterpret_cast<__gm__ float*>(topk_vals_pad_inline110__ssa_v17_tensor->buffer.addr) + topk_vals_pad_inline110__ssa_v17_tensor->start_offset;

    // Unpack tensor: weight_out_pad_inline108__ssa_v0
    __gm__ Tensor* weight_out_pad_inline108__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* weight_out_pad_inline108__ssa_v0 = reinterpret_cast<__gm__ float*>(weight_out_pad_inline108__ssa_v0_tensor->buffer.addr) + weight_out_pad_inline108__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    route_normalize_weights(topk_vals_pad_inline110__ssa_v17, weight_out_pad_inline108__ssa_v0);
}
