// Kernel Function: sh_gate_up_dequant
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void sh_gate_up_dequant(__gm__ float* v1, __gm__ float* v2, __gm__ int32_t* v3, __gm__ int32_t* v4, __gm__ float* v5, __gm__ float* v6, __gm__ float* v7, int32_t v8) {
  RoundMode v9 = RoundMode::CAST_NONE;
  unsigned v10 = 0;
  const int32_t v11 = 256;
  const int32_t v12 = 16;
  const int32_t v13 = 1;
  const int64_t v14 = 18432;
  const int64_t v15 = 2048;
  const int64_t v16 = 1024;
  const int64_t v17 = 0;
  const int64_t v18 = 67584;
  const int64_t v19 = 51200;
  const int64_t v20 = 34816;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v21 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v22 = (uint64_t) v20;
  TASSIGN(v21, v22);
  pto::Shape<1, 1, 1, 16, 256> v23 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v24 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v25 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v3 + (v10 + v10 * (unsigned) v11 + v10 * (unsigned) v13), v23, v24);
  TLOAD(v21, v25);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v27 = (uint64_t) v19;
  TASSIGN(v26, v27);
  pto::Shape<1, 1, 1, 16, 256> v28 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v29 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v30 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v4 + (v10 + v10 * (unsigned) v11 + v10 * (unsigned) v13), v28, v29);
  TLOAD(v26, v30);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v13);
  uint64_t v32 = (uint64_t) v18;
  TASSIGN(v31, v32);
  pto::Shape<1, 1, 1, 16, 1> v33 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v34 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v35 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v5 + (v10 + v10 * (unsigned) v13 + v10 * (unsigned) v12), v33, v34);
  TLOAD(v31, v35);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v37 = (uint64_t) v17;
  TASSIGN(v36, v37);
  pto::Shape<1, 1, 1, 1, 256> v38 = pto::Shape<1, 1, 1, 1, 256>();
  pto::Stride<256, 256, 256, 256, 1> v39 = pto::Stride<256, 256, 256, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND> v40 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND>(v1 + (v10 + (unsigned) v8 * (unsigned) v13), v38, v39);
  TLOAD(v36, v40);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v42 = (uint64_t) v17;
  TASSIGN(v41, v42);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v44 = (uint64_t) v16;
  TASSIGN(v43, v44);
  pto::Shape<1, 1, 1, 1, 256> v45 = pto::Shape<1, 1, 1, 1, 256>();
  pto::Stride<256, 256, 256, 256, 1> v46 = pto::Stride<256, 256, 256, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND> v47 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 256>, pto::Stride<256, 256, 256, 256, 1>, pto::Layout::ND>(v2 + (v10 + (unsigned) v8 * (unsigned) v13), v45, v46);
  TLOAD(v43, v47);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
  Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Vec, float, 1, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v49 = (uint64_t) v16;
  TASSIGN(v48, v49);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v51 = (uint64_t) v15;
  TASSIGN(v50, v51);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v50, v21, v9);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v53 = (uint64_t) v14;
  TASSIGN(v52, v53);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCVT(v52, v26, v9);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v55 = (uint64_t) v15;
  TASSIGN(v54, v55);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  TROWEXPANDMUL(v54, v50, v31);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v57 = (uint64_t) v15;
  TASSIGN(v56, v57);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID3);
  TCOLEXPANDMUL(v56, v54, v41);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v59 = (uint64_t) v14;
  TASSIGN(v58, v59);
  TROWEXPANDMUL(v58, v52, v31);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v61 = (uint64_t) v14;
  TASSIGN(v60, v61);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID4);
  TCOLEXPANDMUL(v60, v58, v48);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  pto::Shape<1, 1, 1, 16, 256> v62 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v63 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v64 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v6 + (v10 + v10 * (unsigned) v11 + v10 * (unsigned) v13), v62, v63);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v64, v56);
  pto::Shape<1, 1, 1, 16, 256> v65 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v66 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v67 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v7 + (v10 + v10 * (unsigned) v11 + v10 * (unsigned) v13), v65, v66);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v67, v60);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: shared_w1_scale__ssa_v0
    __gm__ Tensor* shared_w1_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* shared_w1_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(shared_w1_scale__ssa_v0_tensor->buffer.addr) + shared_w1_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: shared_w3_scale__ssa_v0
    __gm__ Tensor* shared_w3_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* shared_w3_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(shared_w3_scale__ssa_v0_tensor->buffer.addr) + shared_w3_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: sh_gate_acc_inline95__rv_v2
    __gm__ Tensor* sh_gate_acc_inline95__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int32_t* sh_gate_acc_inline95__rv_v2 = reinterpret_cast<__gm__ int32_t*>(sh_gate_acc_inline95__rv_v2_tensor->buffer.addr) + sh_gate_acc_inline95__rv_v2_tensor->start_offset;

    // Unpack tensor: sh_up_acc_inline118__rv_v2
    __gm__ Tensor* sh_up_acc_inline118__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* sh_up_acc_inline118__rv_v2 = reinterpret_cast<__gm__ int32_t*>(sh_up_acc_inline118__rv_v2_tensor->buffer.addr) + sh_up_acc_inline118__rv_v2_tensor->start_offset;

    // Unpack tensor: x_local_scale_dq_inline32__ssa_v0
    __gm__ Tensor* x_local_scale_dq_inline32__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* x_local_scale_dq_inline32__ssa_v0 = reinterpret_cast<__gm__ float*>(x_local_scale_dq_inline32__ssa_v0_tensor->buffer.addr) + x_local_scale_dq_inline32__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[5]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack tensor: ret1__out
    __gm__ Tensor* ret1__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[6]);
    __gm__ float* ret1__out = reinterpret_cast<__gm__ float*>(ret1__out_tensor->buffer.addr) + ret1__out_tensor->start_offset;

    // Unpack scalar: n0_inline113__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline113__idx_v0_conv;
    n0_inline113__idx_v0_conv.u64 = args[7];
    int64_t n0_inline113__idx_v0 = n0_inline113__idx_v0_conv.val;

    // Forward to ptoas-generated function
    sh_gate_up_dequant(shared_w1_scale__ssa_v0, shared_w3_scale__ssa_v0, sh_gate_acc_inline95__rv_v2, sh_up_acc_inline118__rv_v2, x_local_scale_dq_inline32__ssa_v0, ret0__out, ret1__out, n0_inline113__idx_v0);
}
