// Kernel Function: sh_swiglu
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void sh_swiglu(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, int32_t v4) {
  unsigned v5 = 0;
  const float v6 = 1.0f;
  const int32_t v7 = 4096;
  const int32_t v8 = 1;
  const int32_t v9 = 256;
  const int32_t v10 = 16;
  const int64_t v11 = 49152;
  const int64_t v12 = 32768;
  const int64_t v13 = 16384;
  const int64_t v14 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v15 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v16 = (uint64_t) v14;
  TASSIGN(v15, v16);
  pto::Shape<1, 1, 1, 16, 256> v17 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v18 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v19 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v8), v17, v18);
  TLOAD(v15, v19);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v20 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v21 = (uint64_t) v13;
  TASSIGN(v20, v21);
  pto::Shape<1, 1, 1, 16, 256> v22 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v23 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v24 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v2 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v8), v22, v23);
  TLOAD(v20, v24);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v26 = (uint64_t) v12;
  TASSIGN(v25, v26);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TNEG(v25, v15);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v27 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v28 = (uint64_t) v12;
  TASSIGN(v27, v28);
  pipe_barrier(PIPE_V);
  TEXP(v27, v25);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v30 = (uint64_t) v12;
  TASSIGN(v29, v30);
  pipe_barrier(PIPE_V);
  TADDS(v29, v27, v6);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v32 = (uint64_t) v11;
  TASSIGN(v31, v32);
  pipe_barrier(PIPE_V);
  TRECIP(v31, v29);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v34 = (uint64_t) v14;
  TASSIGN(v33, v34);
  pipe_barrier(PIPE_V);
  TMUL(v33, v15, v31);
  Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v9);
  uint64_t v36 = (uint64_t) v14;
  TASSIGN(v35, v36);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TMUL(v35, v33, v20);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v37 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v38 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v39 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v3 + (v5 + v5 * (unsigned) v7 + (unsigned) v4 * (unsigned) v8), v37, v38);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v39, v35);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: sh_gate_v1_inline50__ssa_v0
    __gm__ Tensor* sh_gate_v1_inline50__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* sh_gate_v1_inline50__ssa_v0 = reinterpret_cast<__gm__ float*>(sh_gate_v1_inline50__ssa_v0_tensor->buffer.addr) + sh_gate_v1_inline50__ssa_v0_tensor->start_offset;

    // Unpack tensor: sh_up_v1_inline9__ssa_v0
    __gm__ Tensor* sh_up_v1_inline9__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* sh_up_v1_inline9__ssa_v0 = reinterpret_cast<__gm__ float*>(sh_up_v1_inline9__ssa_v0_tensor->buffer.addr) + sh_up_v1_inline9__ssa_v0_tensor->start_offset;

    // Unpack tensor: sh_tile_fp32_inline88__iter_v1
    __gm__ Tensor* sh_tile_fp32_inline88__iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* sh_tile_fp32_inline88__iter_v1 = reinterpret_cast<__gm__ float*>(sh_tile_fp32_inline88__iter_v1_tensor->buffer.addr) + sh_tile_fp32_inline88__iter_v1_tensor->start_offset;

    // Unpack scalar: n0_inline113__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline113__idx_v0_conv;
    n0_inline113__idx_v0_conv.u64 = args[3];
    int64_t n0_inline113__idx_v0 = n0_inline113__idx_v0_conv.val;

    // Forward to ptoas-generated function
    sh_swiglu(sh_gate_v1_inline50__ssa_v0, sh_up_v1_inline9__ssa_v0, sh_tile_fp32_inline88__iter_v1, n0_inline113__idx_v0);
}
