// Kernel Function: sh_w2_dequant
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void sh_w2_dequant(__gm__ float* v1, __gm__ int32_t* v2, __gm__ float* v3, __gm__ float* v4, int32_t v5) {
  RoundMode v6 = RoundMode::CAST_NONE;
  unsigned v7 = 0;
  const int32_t v8 = 512;
  const int32_t v9 = 16;
  const int32_t v10 = 1;
  const int64_t v11 = 34880;
  const int64_t v12 = 32832;
  const int64_t v13 = 32768;
  const int64_t v14 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v15 = Tile<TileType::Vec, int32_t, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
  uint64_t v16 = (uint64_t) v14;
  TASSIGN(v15, v16);
  pto::Shape<1, 1, 1, 16, 512> v17 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v18 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v19 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v2 + (v7 + v7 * (unsigned) v8 + v7 * (unsigned) v10), v17, v18);
  TLOAD(v15, v19);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v20 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v10);
  uint64_t v21 = (uint64_t) v13;
  TASSIGN(v20, v21);
  pto::Shape<1, 1, 1, 16, 1> v22 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v23 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v24 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v7 + v7 * (unsigned) v10 + v7 * (unsigned) v9), v22, v23);
  TLOAD(v20, v24);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v26 = (uint64_t) v12;
  TASSIGN(v25, v26);
  pto::Shape<1, 1, 1, 1, 512> v27 = pto::Shape<1, 1, 1, 1, 512>();
  pto::Stride<512, 512, 512, 512, 1> v28 = pto::Stride<512, 512, 512, 512, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND> v29 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 512>, pto::Stride<512, 512, 512, 512, 1>, pto::Layout::ND>(v1 + (v7 + (unsigned) v5 * (unsigned) v10), v27, v28);
  TLOAD(v25, v29);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Vec, float, 1, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v8);
  uint64_t v31 = (uint64_t) v12;
  TASSIGN(v30, v31);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
  uint64_t v33 = (uint64_t) v11;
  TASSIGN(v32, v33);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TCVT(v32, v15, v6);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
  uint64_t v35 = (uint64_t) v11;
  TASSIGN(v34, v35);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TROWEXPANDMUL(v34, v32, v20);
  Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 16, 512, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v8);
  uint64_t v37 = (uint64_t) v11;
  TASSIGN(v36, v37);
  pipe_barrier(PIPE_V);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID2);
  TCOLEXPANDMUL(v36, v34, v30);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 512> v38 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v39 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v40 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v4 + (v7 + v7 * (unsigned) v8 + v7 * (unsigned) v10), v38, v39);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v40, v36);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: shared_w2_scale__ssa_v0
    __gm__ Tensor* shared_w2_scale__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* shared_w2_scale__ssa_v0 = reinterpret_cast<__gm__ float*>(shared_w2_scale__ssa_v0_tensor->buffer.addr) + shared_w2_scale__ssa_v0_tensor->start_offset;

    // Unpack tensor: sh_y_acc_inline4__rv_v2
    __gm__ Tensor* sh_y_acc_inline4__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* sh_y_acc_inline4__rv_v2 = reinterpret_cast<__gm__ int32_t*>(sh_y_acc_inline4__rv_v2_tensor->buffer.addr) + sh_y_acc_inline4__rv_v2_tensor->start_offset;

    // Unpack tensor: sh_tile_scale_dq_inline99__ssa_v0
    __gm__ Tensor* sh_tile_scale_dq_inline99__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* sh_tile_scale_dq_inline99__ssa_v0 = reinterpret_cast<__gm__ float*>(sh_tile_scale_dq_inline99__ssa_v0_tensor->buffer.addr) + sh_tile_scale_dq_inline99__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: d0_inline64__idx_v0
    union { uint64_t u64; int64_t val; } d0_inline64__idx_v0_conv;
    d0_inline64__idx_v0_conv.u64 = args[4];
    int64_t d0_inline64__idx_v0 = d0_inline64__idx_v0_conv.val;

    // Forward to ptoas-generated function
    sh_w2_dequant(shared_w2_scale__ssa_v0, sh_y_acc_inline4__rv_v2, sh_tile_scale_dq_inline99__ssa_v0, ret0__out, d0_inline64__idx_v0);
}
