// Kernel Function: split_pre_post_1
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void split_pre_post_1(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, __gm__ float* v5, float v6) {
  unsigned v7 = 0;
  const float v8 = 2.0f;
  const float v9 = 1.0f;
  const int32_t v10 = 1;
  const int32_t v11 = 32;
  const int32_t v12 = 8;
  const int32_t v13 = 16;
  const int64_t v14 = 0;
  const int64_t v15 = 2048;
  const int64_t v16 = 1536;
  const int64_t v17 = 1024;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v18 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v19 = (uint64_t) v17;
  TASSIGN(v18, v19);
  pto::Shape<1, 1, 1, 16, 8> v20 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<512, 512, 512, 32, 1> v21 = pto::Stride<512, 512, 512, 32, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v22 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(v1 + (v7 + v7 * (unsigned) v11 + v7 * (unsigned) v10), v20, v21);
  TLOAD(v18, v22);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v24 = (uint64_t) v16;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 16, 8> v25 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<128, 128, 128, 8, 1> v26 = pto::Stride<128, 128, 128, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND>(v2 + (v7 + v7 * (unsigned) v12 + v7 * (unsigned) v10), v25, v26);
  TLOAD(v23, v27);
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v10, v12);
  uint64_t v29 = (uint64_t) v15;
  TASSIGN(v28, v29);
  pto::Shape<1, 1, 1, 1, 8> v30 = pto::Shape<1, 1, 1, 1, 8>();
  pto::Stride<8, 8, 8, 8, 1> v31 = pto::Stride<8, 8, 8, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v32 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(v3 + (v7 + v7 * (unsigned) v12 + v7 * (unsigned) v10), v30, v31);
  TLOAD(v28, v32);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v34 = (uint64_t) v17;
  TASSIGN(v33, v34);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TMULS(v33, v18, v6);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v36 = (uint64_t) v16;
  TASSIGN(v35, v36);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v35, v23, v28);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v38 = (uint64_t) v17;
  TASSIGN(v37, v38);
  pipe_barrier(PIPE_V);
  TADD(v37, v33, v35);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v40 = (uint64_t) v17;
  TASSIGN(v39, v40);
  pipe_barrier(PIPE_V);
  TNEG(v39, v37);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v42 = (uint64_t) v17;
  TASSIGN(v41, v42);
  pipe_barrier(PIPE_V);
  TEXP(v41, v39);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v44 = (uint64_t) v17;
  TASSIGN(v43, v44);
  pipe_barrier(PIPE_V);
  TADDS(v43, v41, v9);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v46 = (uint64_t) v16;
  TASSIGN(v45, v46);
  pipe_barrier(PIPE_V);
  TRECIP(v45, v43);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v12);
  uint64_t v48 = (uint64_t) v17;
  TASSIGN(v47, v48);
  pipe_barrier(PIPE_V);
  TMULS(v47, v45, v8);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v49 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v13);
  uint64_t v50 = (uint64_t) v14;
  TASSIGN(v49, v50);
  TEXPANDS(v49, v9);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  pto::Shape<1, 1, 1, 16, 8> v51 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<128, 128, 128, 8, 1> v52 = pto::Stride<128, 128, 128, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND> v53 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND>(v4 + (v7 + v7 * (unsigned) v12 + v7 * (unsigned) v10), v51, v52);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v53, v47);
  pto::Shape<1, 1, 1, 16, 16> v54 = pto::Shape<1, 1, 1, 16, 16>();
  pto::Stride<256, 256, 256, 16, 1> v55 = pto::Stride<256, 256, 256, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND> v56 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND>(v5 + (v7 + v7 * (unsigned) v13 + v7 * (unsigned) v10), v54, v55);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v56, v49);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: t__tmp_v34
    __gm__ Tensor* t__tmp_v34_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* t__tmp_v34 = reinterpret_cast<__gm__ float*>(t__tmp_v34_tensor->buffer.addr) + t__tmp_v34_tensor->start_offset;

    // Unpack tensor: ones_hc_inline79__ssa_v0
    __gm__ Tensor* ones_hc_inline79__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* ones_hc_inline79__ssa_v0 = reinterpret_cast<__gm__ float*>(ones_hc_inline79__ssa_v0_tensor->buffer.addr) + ones_hc_inline79__ssa_v0_tensor->start_offset;

    // Unpack tensor: post_base_inline50__ssa_v0
    __gm__ Tensor* post_base_inline50__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* post_base_inline50__ssa_v0 = reinterpret_cast<__gm__ float*>(post_base_inline50__ssa_v0_tensor->buffer.addr) + post_base_inline50__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack tensor: ret1__out
    __gm__ Tensor* ret1__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ float* ret1__out = reinterpret_cast<__gm__ float*>(ret1__out_tensor->buffer.addr) + ret1__out_tensor->start_offset;

    // Unpack scalar: scale1_inline17__ssa_v0
    union { uint64_t u64; float val; } scale1_inline17__ssa_v0_conv;
    scale1_inline17__ssa_v0_conv.u64 = args[5];
    float scale1_inline17__ssa_v0 = scale1_inline17__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    split_pre_post_1(t__tmp_v34, ones_hc_inline79__ssa_v0, post_base_inline50__ssa_v0, ret0__out, ret1__out, scale1_inline17__ssa_v0);
}
