// Kernel Function: split_pre_post
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void split_pre_post(__gm__ float* v1) {
  unsigned v2 = 0;
  const float v3 = 1.0f;
  const int32_t v4 = 1;
  const int32_t v5 = 8;
  const int32_t v6 = 16;
  const int64_t v7 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v8 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v6, v5);
  uint64_t v9 = (uint64_t) v7;
  TASSIGN(v8, v9);
  TEXPANDS(v8, v3);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 8> v10 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<128, 128, 128, 8, 1> v11 = pto::Stride<128, 128, 128, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND> v12 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND>(v1 + (v2 + v2 * (unsigned) v5 + v2 * (unsigned) v4), v10, v11);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v12, v8);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Forward to ptoas-generated function
    split_pre_post(ret0__out);
}
