// Kernel Function: split_pre_post_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void split_pre_post_0(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, float v5) {
  unsigned v6 = 0;
  const float v7 = 9.99999997E-7f;
  const float v8 = 1.0f;
  const int32_t v9 = 1;
  const int32_t v10 = 32;
  const int32_t v11 = 8;
  const int32_t v12 = 16;
  const int64_t v13 = 1024;
  const int64_t v14 = 512;
  const int64_t v15 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v16 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v17 = (uint64_t) v15;
  TASSIGN(v16, v17);
  pto::Shape<1, 1, 1, 16, 8> v18 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<512, 512, 512, 32, 1> v19 = pto::Stride<512, 512, 512, 32, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v20 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v10 + v6 * (unsigned) v9), v18, v19);
  TLOAD(v16, v20);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v21 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v22 = (uint64_t) v14;
  TASSIGN(v21, v22);
  pto::Shape<1, 1, 1, 16, 8> v23 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<128, 128, 128, 8, 1> v24 = pto::Stride<128, 128, 128, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND> v25 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND>(v2 + (v6 + v6 * (unsigned) v11 + v6 * (unsigned) v9), v23, v24);
  TLOAD(v21, v25);
  Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, float, 1, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v11);
  uint64_t v27 = (uint64_t) v13;
  TASSIGN(v26, v27);
  pto::Shape<1, 1, 1, 1, 8> v28 = pto::Shape<1, 1, 1, 1, 8>();
  pto::Stride<8, 8, 8, 8, 1> v29 = pto::Stride<8, 8, 8, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND> v30 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 8>, pto::Stride<8, 8, 8, 8, 1>, pto::Layout::ND>(v3 + (v6 + v6 * (unsigned) v11 + v6 * (unsigned) v9), v28, v29);
  TLOAD(v26, v30);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v31 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v32 = (uint64_t) v15;
  TASSIGN(v31, v32);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TMULS(v31, v16, v5);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v33 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v34 = (uint64_t) v14;
  TASSIGN(v33, v34);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v33, v21, v26);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v35 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v36 = (uint64_t) v15;
  TASSIGN(v35, v36);
  pipe_barrier(PIPE_V);
  TADD(v35, v31, v33);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v38 = (uint64_t) v15;
  TASSIGN(v37, v38);
  pipe_barrier(PIPE_V);
  TNEG(v37, v35);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v40 = (uint64_t) v15;
  TASSIGN(v39, v40);
  pipe_barrier(PIPE_V);
  TEXP(v39, v37);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v42 = (uint64_t) v15;
  TASSIGN(v41, v42);
  pipe_barrier(PIPE_V);
  TADDS(v41, v39, v8);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v44 = (uint64_t) v14;
  TASSIGN(v43, v44);
  pipe_barrier(PIPE_V);
  TRECIP(v43, v41);
  Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Vec, float, 16, 8, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v12, v11);
  uint64_t v46 = (uint64_t) v15;
  TASSIGN(v45, v46);
  pipe_barrier(PIPE_V);
  TADDS(v45, v43, v7);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 8> v47 = pto::Shape<1, 1, 1, 16, 8>();
  pto::Stride<128, 128, 128, 8, 1> v48 = pto::Stride<128, 128, 128, 8, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND> v49 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 8>, pto::Stride<128, 128, 128, 8, 1>, pto::Layout::ND>(v4 + (v6 + v6 * (unsigned) v11 + v6 * (unsigned) v9), v47, v48);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v49, v45);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: t__tmp_v26
    __gm__ Tensor* t__tmp_v26_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* t__tmp_v26 = reinterpret_cast<__gm__ float*>(t__tmp_v26_tensor->buffer.addr) + t__tmp_v26_tensor->start_offset;

    // Unpack tensor: ones_hc_inline79__ssa_v0
    __gm__ Tensor* ones_hc_inline79__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* ones_hc_inline79__ssa_v0 = reinterpret_cast<__gm__ float*>(ones_hc_inline79__ssa_v0_tensor->buffer.addr) + ones_hc_inline79__ssa_v0_tensor->start_offset;

    // Unpack tensor: pre_base_inline76__ssa_v0
    __gm__ Tensor* pre_base_inline76__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* pre_base_inline76__ssa_v0 = reinterpret_cast<__gm__ float*>(pre_base_inline76__ssa_v0_tensor->buffer.addr) + pre_base_inline76__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: scale0_inline21__ssa_v0
    union { uint64_t u64; float val; } scale0_inline21__ssa_v0_conv;
    scale0_inline21__ssa_v0_conv.u64 = args[4];
    float scale0_inline21__ssa_v0 = scale0_inline21__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    split_pre_post_0(t__tmp_v26, ones_hc_inline79__ssa_v0, pre_base_inline76__ssa_v0, ret0__out, scale0_inline21__ssa_v0);
}
