// Kernel Function: split_pre_post_2
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void split_pre_post_2(__gm__ float* v1, __gm__ float* v2, __gm__ float* v3, __gm__ float* v4, float v5) {
  unsigned v6 = 0;
  const int32_t v7 = 1;
  const int32_t v8 = 32;
  const int32_t v9 = 16;
  const int64_t v10 = 2048;
  const int64_t v11 = 1024;
  const int64_t v12 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v13 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v14 = (uint64_t) v12;
  TASSIGN(v13, v14);
  pto::Shape<1, 1, 1, 16, 16> v15 = pto::Shape<1, 1, 1, 16, 16>();
  pto::Stride<512, 512, 512, 32, 1> v16 = pto::Stride<512, 512, 512, 32, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v17 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v8 + v6 * (unsigned) v7), v15, v16);
  TLOAD(v13, v17);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v18 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v19 = (uint64_t) v11;
  TASSIGN(v18, v19);
  pto::Shape<1, 1, 1, 16, 16> v20 = pto::Shape<1, 1, 1, 16, 16>();
  pto::Stride<256, 256, 256, 16, 1> v21 = pto::Stride<256, 256, 256, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND> v22 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND>(v2 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v7), v20, v21);
  TLOAD(v18, v22);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v23 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v7, v9);
  uint64_t v24 = (uint64_t) v10;
  TASSIGN(v23, v24);
  pto::Shape<1, 1, 1, 1, 16> v25 = pto::Shape<1, 1, 1, 1, 16>();
  pto::Stride<16, 16, 16, 16, 1> v26 = pto::Stride<16, 16, 16, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND> v27 = GlobalTensor<float, pto::Shape<1, 1, 1, 1, 16>, pto::Stride<16, 16, 16, 16, 1>, pto::Layout::ND>(v3 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v7), v25, v26);
  TLOAD(v23, v27);
  set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v28 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v29 = (uint64_t) v12;
  TASSIGN(v28, v29);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
  TMULS(v28, v13, v5);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v31 = (uint64_t) v11;
  TASSIGN(v30, v31);
  wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
  TCOLEXPANDMUL(v30, v18, v23);
  Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Vec, float, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v33 = (uint64_t) v12;
  TASSIGN(v32, v33);
  pipe_barrier(PIPE_V);
  TADD(v32, v28, v30);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 16> v34 = pto::Shape<1, 1, 1, 16, 16>();
  pto::Stride<256, 256, 256, 16, 1> v35 = pto::Stride<256, 256, 256, 16, 1>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND> v36 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND>(v4 + (v6 + v6 * (unsigned) v9 + v6 * (unsigned) v7), v34, v35);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
  TSTORE(v36, v32);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: comb_mix_inline41__ssa_v0
    __gm__ Tensor* comb_mix_inline41__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* comb_mix_inline41__ssa_v0 = reinterpret_cast<__gm__ float*>(comb_mix_inline41__ssa_v0_tensor->buffer.addr) + comb_mix_inline41__ssa_v0_tensor->start_offset;

    // Unpack tensor: ones_comb_inline67__ssa_v0
    __gm__ Tensor* ones_comb_inline67__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* ones_comb_inline67__ssa_v0 = reinterpret_cast<__gm__ float*>(ones_comb_inline67__ssa_v0_tensor->buffer.addr) + ones_comb_inline67__ssa_v0_tensor->start_offset;

    // Unpack tensor: comb_base_inline70__ssa_v0
    __gm__ Tensor* comb_base_inline70__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* comb_base_inline70__ssa_v0 = reinterpret_cast<__gm__ float*>(comb_base_inline70__ssa_v0_tensor->buffer.addr) + comb_base_inline70__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: scale2_inline26__ssa_v0
    union { uint64_t u64; float val; } scale2_inline26__ssa_v0_conv;
    scale2_inline26__ssa_v0_conv.u64 = args[4];
    float scale2_inline26__ssa_v0 = scale2_inline26__ssa_v0_conv.val;

    // Forward to ptoas-generated function
    split_pre_post_2(comb_mix_inline41__ssa_v0, ones_comb_inline67__ssa_v0, comb_base_inline70__ssa_v0, ret0__out, scale2_inline26__ssa_v0);
}
