// Kernel Function: write_post
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void write_post(__gm__ float* v1, __gm__ float* v2, int32_t v3) {
  const int32_t v4 = 3;
  const int32_t v5 = 2;
  const int32_t v6 = 4;
  const int32_t v7 = 8;
  const int32_t v8 = 16;
  const int32_t v9 = 0;
  const int32_t v10 = 1;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  for (size_t v11 = (size_t) v9; v11 < ((size_t) v8); v11 += (size_t) v10) {
    int32_t v12 = (int32_t) ((uint32_t) ((int32_t) (uint32_t) v3 * (uint32_t) v8) + (uint32_t) ((int32_t) v11));
    if (v12 < v8) {
      int32_t v13 = (int32_t) ((uint32_t) v12 * (uint32_t) v7);
      float v14 = v1[v13];
      int32_t v15 = (int32_t) ((uint32_t) v12 * (uint32_t) v6);
      v2[v15] = v14;
      float v16 = v1[(int32_t) ((uint32_t) v13 + (uint32_t) v10)];
      int32_t v17 = (int32_t) ((uint32_t) v15 + (uint32_t) v10);
      v2[v17] = v16;
      float v18 = v1[(int32_t) ((uint32_t) v13 + (uint32_t) v5)];
      int32_t v19 = (int32_t) ((uint32_t) v15 + (uint32_t) v5);
      v2[v19] = v18;
      float v20 = v1[(int32_t) ((uint32_t) v13 + (uint32_t) v4)];
      int32_t v21 = (int32_t) ((uint32_t) v15 + (uint32_t) v4);
      v2[v21] = v20;
    };
  }
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: post_pad_flat_inline73__ssa_v0
    __gm__ Tensor* post_pad_flat_inline73__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* post_pad_flat_inline73__ssa_v0 = reinterpret_cast<__gm__ float*>(post_pad_flat_inline73__ssa_v0_tensor->buffer.addr) + post_pad_flat_inline73__ssa_v0_tensor->start_offset;

    // Unpack tensor: post_flat_inline51__ssa_v0
    __gm__ Tensor* post_flat_inline51__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ float* post_flat_inline51__ssa_v0 = reinterpret_cast<__gm__ float*>(post_flat_inline51__ssa_v0_tensor->buffer.addr) + post_flat_inline51__ssa_v0_tensor->start_offset;

    // Unpack scalar: t_inline7__co_idx_v0
    union { uint64_t u64; int64_t val; } t_inline7__co_idx_v0_conv;
    t_inline7__co_idx_v0_conv.u64 = args[2];
    int64_t t_inline7__co_idx_v0 = t_inline7__co_idx_v0_conv.val;

    // Forward to ptoas-generated function
    write_post(post_pad_flat_inline73__ssa_v0, post_flat_inline51__ssa_v0, t_inline7__co_idx_v0);
}
