// Kernel Function: write_route_outputs
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"
#include "aicore/aicore.h"  // dcci — flush scalar writes out of L1 so the
                            // downstream dispatch kernel sees them via scalar
                            // reads. Without this, indices/weights stay in
                            // this core's data cache and dispatch races
                            // ~60% of runs in onboard mode.


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void write_route_outputs(__gm__ int32_t* v1, __gm__ int32_t* v2, __gm__ float* v3, __gm__ float* v4) {
  const int32_t v5 = 31;
  const int32_t v6 = 481;
  const int32_t v7 = 30;
  const int32_t v8 = 480;
  const int32_t v9 = 29;
  const int32_t v10 = 449;
  const int32_t v11 = 28;
  const int32_t v12 = 448;
  const int32_t v13 = 27;
  const int32_t v14 = 417;
  const int32_t v15 = 26;
  const int32_t v16 = 416;
  const int32_t v17 = 25;
  const int32_t v18 = 385;
  const int32_t v19 = 24;
  const int32_t v20 = 384;
  const int32_t v21 = 23;
  const int32_t v22 = 353;
  const int32_t v23 = 22;
  const int32_t v24 = 352;
  const int32_t v25 = 21;
  const int32_t v26 = 321;
  const int32_t v27 = 20;
  const int32_t v28 = 320;
  const int32_t v29 = 19;
  const int32_t v30 = 289;
  const int32_t v31 = 18;
  const int32_t v32 = 288;
  const int32_t v33 = 17;
  const int32_t v34 = 257;
  const int32_t v35 = 16;
  const int32_t v36 = 256;
  const int32_t v37 = 15;
  const int32_t v38 = 225;
  const int32_t v39 = 14;
  const int32_t v40 = 224;
  const int32_t v41 = 13;
  const int32_t v42 = 193;
  const int32_t v43 = 12;
  const int32_t v44 = 192;
  const int32_t v45 = 11;
  const int32_t v46 = 161;
  const int32_t v47 = 10;
  const int32_t v48 = 160;
  const int32_t v49 = 9;
  const int32_t v50 = 129;
  const int32_t v51 = 8;
  const int32_t v52 = 128;
  const int32_t v53 = 7;
  const int32_t v54 = 97;
  const int32_t v55 = 6;
  const int32_t v56 = 96;
  const int32_t v57 = 5;
  const int32_t v58 = 65;
  const int32_t v59 = 4;
  const int32_t v60 = 64;
  const int32_t v61 = 3;
  const int32_t v62 = 33;
  const int32_t v63 = 2;
  const int32_t v64 = 0;
  const int32_t v65 = 32;
  const int32_t v66 = 1;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  int32_t v67 = v1[v64];
  v2[v64] = v67;
  float v68 = v3[v64];
  v4[v64] = v68;
  int32_t v69 = v1[v66];
  v2[v66] = v69;
  float v70 = v3[v66];
  v4[v66] = v70;
  int32_t v71 = v1[v65];
  v2[v63] = v71;
  float v72 = v3[v65];
  v4[v63] = v72;
  int32_t v73 = v1[v62];
  v2[v61] = v73;
  float v74 = v3[v62];
  v4[v61] = v74;
  int32_t v75 = v1[v60];
  v2[v59] = v75;
  float v76 = v3[v60];
  v4[v59] = v76;
  int32_t v77 = v1[v58];
  v2[v57] = v77;
  float v78 = v3[v58];
  v4[v57] = v78;
  int32_t v79 = v1[v56];
  v2[v55] = v79;
  float v80 = v3[v56];
  v4[v55] = v80;
  int32_t v81 = v1[v54];
  v2[v53] = v81;
  float v82 = v3[v54];
  v4[v53] = v82;
  int32_t v83 = v1[v52];
  v2[v51] = v83;
  float v84 = v3[v52];
  v4[v51] = v84;
  int32_t v85 = v1[v50];
  v2[v49] = v85;
  float v86 = v3[v50];
  v4[v49] = v86;
  int32_t v87 = v1[v48];
  v2[v47] = v87;
  float v88 = v3[v48];
  v4[v47] = v88;
  int32_t v89 = v1[v46];
  v2[v45] = v89;
  float v90 = v3[v46];
  v4[v45] = v90;
  int32_t v91 = v1[v44];
  v2[v43] = v91;
  float v92 = v3[v44];
  v4[v43] = v92;
  int32_t v93 = v1[v42];
  v2[v41] = v93;
  float v94 = v3[v42];
  v4[v41] = v94;
  int32_t v95 = v1[v40];
  v2[v39] = v95;
  float v96 = v3[v40];
  v4[v39] = v96;
  int32_t v97 = v1[v38];
  v2[v37] = v97;
  float v98 = v3[v38];
  v4[v37] = v98;
  int32_t v99 = v1[v36];
  v2[v35] = v99;
  float v100 = v3[v36];
  v4[v35] = v100;
  int32_t v101 = v1[v34];
  v2[v33] = v101;
  float v102 = v3[v34];
  v4[v33] = v102;
  int32_t v103 = v1[v32];
  v2[v31] = v103;
  float v104 = v3[v32];
  v4[v31] = v104;
  int32_t v105 = v1[v30];
  v2[v29] = v105;
  float v106 = v3[v30];
  v4[v29] = v106;
  int32_t v107 = v1[v28];
  v2[v27] = v107;
  float v108 = v3[v28];
  v4[v27] = v108;
  int32_t v109 = v1[v26];
  v2[v25] = v109;
  float v110 = v3[v26];
  v4[v25] = v110;
  int32_t v111 = v1[v24];
  v2[v23] = v111;
  float v112 = v3[v24];
  v4[v23] = v112;
  int32_t v113 = v1[v22];
  v2[v21] = v113;
  float v114 = v3[v22];
  v4[v21] = v114;
  int32_t v115 = v1[v20];
  v2[v19] = v115;
  float v116 = v3[v20];
  v4[v19] = v116;
  int32_t v117 = v1[v18];
  v2[v17] = v117;
  float v118 = v3[v18];
  v4[v17] = v118;
  int32_t v119 = v1[v16];
  v2[v15] = v119;
  float v120 = v3[v16];
  v4[v15] = v120;
  int32_t v121 = v1[v14];
  v2[v13] = v121;
  float v122 = v3[v14];
  v4[v13] = v122;
  int32_t v123 = v1[v12];
  v2[v11] = v123;
  float v124 = v3[v12];
  v4[v11] = v124;
  int32_t v125 = v1[v10];
  v2[v9] = v125;
  float v126 = v3[v10];
  v4[v9] = v126;
  int32_t v127 = v1[v8];
  v2[v7] = v127;
  float v128 = v3[v8];
  v4[v7] = v128;
  int32_t v129 = v1[v6];
  v2[v5] = v129;
  float v130 = v3[v6];
  v4[v5] = v130;
  // Flush scalar writes (indices, weights) out of this AICore's L1 so the
  // downstream dispatch task sees them when it scalar-reads `indices`. The
  // PyPTO-emitted body has no tail sync, and dispatch's reader-side dcci on
  // its own only invalidates the reader cache — both sides must participate.
  pipe_barrier(PIPE_ALL);
  dcci(v2, ENTIRE_DATA_CACHE, CACHELINE_OUT);
  dcci(v4, ENTIRE_DATA_CACHE, CACHELINE_OUT);
  dsb((mem_dsb_t)0);
  #endif // __DAV_VEC__

  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: topk_idx_flat_inline87__ssa_v0
    __gm__ Tensor* topk_idx_flat_inline87__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int32_t* topk_idx_flat_inline87__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(topk_idx_flat_inline87__ssa_v0_tensor->buffer.addr) + topk_idx_flat_inline87__ssa_v0_tensor->start_offset;

    // Unpack tensor: indices_flat_inline89__ssa_v0
    __gm__ Tensor* indices_flat_inline89__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int32_t* indices_flat_inline89__ssa_v0 = reinterpret_cast<__gm__ int32_t*>(indices_flat_inline89__ssa_v0_tensor->buffer.addr) + indices_flat_inline89__ssa_v0_tensor->start_offset;

    // Unpack tensor: weight_out_flat_inline86__ssa_v0
    __gm__ Tensor* weight_out_flat_inline86__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* weight_out_flat_inline86__ssa_v0 = reinterpret_cast<__gm__ float*>(weight_out_flat_inline86__ssa_v0_tensor->buffer.addr) + weight_out_flat_inline86__ssa_v0_tensor->start_offset;

    // Unpack tensor: weights_flat_inline88__ssa_v0
    __gm__ Tensor* weights_flat_inline88__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ float* weights_flat_inline88__ssa_v0 = reinterpret_cast<__gm__ float*>(weights_flat_inline88__ssa_v0_tensor->buffer.addr) + weights_flat_inline88__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    write_route_outputs(topk_idx_flat_inline87__ssa_v0, indices_flat_inline89__ssa_v0, weight_out_flat_inline86__ssa_v0, weights_flat_inline88__ssa_v0);
}
