// Kernel Function: x_local_q
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void x_local_q(__gm__ bfloat16_t* v1, __gm__ int8_t* v2, __gm__ float* v3) {
  RoundMode v4 = RoundMode::CAST_TRUNC;
  RoundMode v5 = RoundMode::CAST_ROUND;
  unsigned v6 = 0;
  const float v7 = 127.0f;
  const int32_t v8 = 256;
  const int32_t v9 = 0;
  const float v10 = 9.99999974E-5f;
  const int32_t v11 = 1;
  const int32_t v12 = 4096;
  const int32_t v13 = 16;
  const int64_t v14 = 24640;
  const int64_t v15 = 16448;
  const int64_t v16 = 64;
  const int64_t v17 = 0;
  const int64_t v18 = 69760;
  const int64_t v19 = 53376;
  const int64_t v20 = 36992;
  const int64_t v21 = 28800;
  const int64_t v22 = 28736;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v23 = (size_t) v12;
  size_t v24 = (size_t) v9;
  size_t v25 = (size_t) v8;
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v26 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v27 = (uint64_t) v22;
  TASSIGN(v26, v27);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  TEXPANDS(v26, v10);
  for (size_t v28 = v24; v28 < v23; v28 += v25) {
    Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v30 = (uint64_t) v21;
    TASSIGN(v29, v30);
    pto::Shape<1, 1, 1, 16, 256> v31 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v32 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v33 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v12 + (unsigned) ((int32_t) v28) * (unsigned) v11), v31, v32);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    TLOAD(v29, v33);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v35 = (uint64_t) v20;
    TASSIGN(v34, v35);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TCVT(v34, v29, v5);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v37 = (uint64_t) v19;
    TASSIGN(v36, v37);
    pipe_barrier(PIPE_V);
    TNEG(v36, v34);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v39 = (uint64_t) v20;
    TASSIGN(v38, v39);
    pipe_barrier(PIPE_V);
    TMAX(v38, v34, v36);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v40 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v41 = (uint64_t) v19;
    TASSIGN(v40, v41);
    Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v42 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
    uint64_t v43 = (uint64_t) v18;
    TASSIGN(v42, v43);
    pipe_barrier(PIPE_V);
    TROWMAX(v42, v38, v40);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v44 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v45 = (uint64_t) v18;
    TASSIGN(v44, v45);
    Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v46 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v47 = (uint64_t) v22;
    TASSIGN(v46, v47);
    pipe_barrier(PIPE_V);
    TMAX(v46, v26, v44);
  }
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v49 = (uint64_t) v17;
  TASSIGN(v48, v49);
  TEXPANDS(v48, v7);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v51 = (uint64_t) v22;
  TASSIGN(v50, v51);
  pipe_barrier(PIPE_V);
  TDIV(v50, v48, v26);
  Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Vec, float, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v53 = (uint64_t) v17;
  TASSIGN(v52, v53);
  pipe_barrier(PIPE_V);
  TRECIP(v52, v50);
  set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v55 = (uint64_t) v17;
  TASSIGN(v54, v55);
  Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Vec, float, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v11);
  uint64_t v57 = (uint64_t) v22;
  TASSIGN(v56, v57);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  for (size_t v58 = v24; v58 < v23; v58 += v25) {
    int32_t v59 = (int32_t) v58;
    Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v60 = Tile<TileType::Vec, bfloat16_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v61 = (uint64_t) v21;
    TASSIGN(v60, v61);
    pto::Shape<1, 1, 1, 16, 256> v62 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v63 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v64 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v6 + v6 * (unsigned) v12 + (unsigned) v59 * (unsigned) v11), v62, v63);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v60, v64);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v65 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v66 = (uint64_t) v20;
    TASSIGN(v65, v66);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TCVT(v65, v60, v5);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Vec, float, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v68 = (uint64_t) v20;
    TASSIGN(v67, v68);
    pipe_barrier(PIPE_V);
    TROWEXPANDMUL(v67, v65, v56);
    Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Vec, int32_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v70 = (uint64_t) v16;
    TASSIGN(v69, v70);
    pipe_barrier(PIPE_V);
    TCVT(v69, v67, v5);
    Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Vec, half, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v72 = (uint64_t) v15;
    TASSIGN(v71, v72);
    pipe_barrier(PIPE_V);
    TCVT(v71, v69, v5);
    Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Vec, int8_t, 16, 256, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null, CompactMode::Null>(v13, v8);
    uint64_t v74 = (uint64_t) v14;
    TASSIGN(v73, v74);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TCVT(v73, v71, v4);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pto::Shape<1, 1, 1, 16, 256> v75 = pto::Shape<1, 1, 1, 16, 256>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v76 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v77 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v2 + (v6 + v6 * (unsigned) v12 + (unsigned) v59 * (unsigned) v11), v75, v76);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v77, v73);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  }
  pto::Shape<1, 1, 1, 16, 1> v78 = pto::Shape<1, 1, 1, 16, 1>();
  pto::Stride<16, 16, 16, 1, 16> v79 = pto::Stride<16, 16, 16, 1, 16>();
  GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN> v80 = GlobalTensor<float, pto::Shape<1, 1, 1, 16, 1>, pto::Stride<16, 16, 16, 1, 16>, pto::Layout::DN>(v3 + (v6 + v6 * (unsigned) v11 + v6 * (unsigned) v13), v78, v79);
  wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
  TSTORE(v80, v54);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_local__ssa_v0
    __gm__ Tensor* x_local__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ bfloat16_t* x_local__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(x_local__ssa_v0_tensor->buffer.addr) + x_local__ssa_v0_tensor->start_offset;

    // Unpack tensor: x_local_i8_inline43__ssa_v0
    __gm__ Tensor* x_local_i8_inline43__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* x_local_i8_inline43__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(x_local_i8_inline43__ssa_v0_tensor->buffer.addr) + x_local_i8_inline43__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* ret0__out = reinterpret_cast<__gm__ float*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Forward to ptoas-generated function
    x_local_q(x_local__ssa_v0, x_local_i8_inline43__ssa_v0, ret0__out);
}
