// Kernel Function: exp_gate_up_matmul
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void exp_gate_up_matmul(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int32_t* v5, int32_t v6, int32_t v7) {
  unsigned v8 = 0;
  const int32_t v9 = 128;
  const int32_t v10 = 0;
  const int32_t v11 = 512;
  const int32_t v12 = 16777216;
  const int32_t v13 = 256;
  const int32_t v14 = 1;
  const int32_t v15 = 4096;
  const int32_t v16 = 16;
  const int64_t v17 = 32768;
  const int64_t v18 = 2048;
  const int64_t v19 = 16384;
  const int64_t v20 = 8192;
  const int64_t v21 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  size_t v22 = (size_t) v13;
  size_t v23 = (size_t) v11;
  size_t v24 = (size_t) v10;
  Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
  uint64_t v26 = (uint64_t) v21;
  TASSIGN(v25, v26);
  pto::Shape<1, 1, 1, 16, 512> v27 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v28 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v29 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v8 + v8 * (unsigned) v15 + v8 * (unsigned) v14), v27, v28);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  TLOAD(v25, v29);
  Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
  uint64_t v31 = (uint64_t) v21;
  TASSIGN(v30, v31);
  pipe_barrier(PIPE_MTE2);
  TLOAD(v30, v29);
  Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v32 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v33 = (uint64_t) v20;
  TASSIGN(v32, v33);
  pto::Shape<1, 1, 1, 512, 256> v34 = pto::Shape<1, 1, 1, 512, 256>();
  pto::Stride<16777216, 16777216, 16777216, 1, 4096> v35 = pto::Stride<16777216, 16777216, 16777216, 1, 4096>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN> v36 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN>(v2 + ((v8 + (unsigned) v6 * (unsigned) v12) + v8 * (unsigned) v14 + (unsigned) v7 * (unsigned) v15), v34, v35);
  TLOAD(v32, v36);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v37 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
  uint64_t v38 = (uint64_t) v19;
  TASSIGN(v37, v38);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  for (size_t v39 = v24; v39 < v23; v39 += v22) {
    int32_t v40 = (int32_t) v39;
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v42 = (uint64_t) v18;
    TASSIGN(v41, v42);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    pipe_barrier(PIPE_MTE1);
    TEXTRACT(v41, v30, v10, v39);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
    uint64_t v44 = (uint64_t) v21;
    TASSIGN(v43, v44);
    TEXTRACT(v43, v32, v39, v10);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v46 = (uint64_t) v21;
    TASSIGN(v45, v46);
    int32_t v47 = (int32_t) ((uint32_t) v40 + (uint32_t) v9);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    TEXTRACT(v45, v30, v10, v47);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v48 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
    uint64_t v49 = (uint64_t) v17;
    TASSIGN(v48, v49);
    TEXTRACT(v48, v32, v47, v10);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    if (v40 == v10) {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v51 = (uint64_t) v19;
      TASSIGN(v50, v51);
      pipe_barrier(PIPE_M);
      TMATMUL(v50, v41, v43);
    } else {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v53 = (uint64_t) v19;
      TASSIGN(v52, v53);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v52, v52, v41, v43);
    };
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
    uint64_t v55 = (uint64_t) v19;
    TASSIGN(v54, v55);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    TMATMUL_ACC(v54, v54, v45, v48);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
  uint64_t v57 = (uint64_t) v21;
  TASSIGN(v56, v57);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  pipe_barrier(PIPE_MTE2);
  TLOAD(v56, v29);
  Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v11, v13);
  uint64_t v59 = (uint64_t) v20;
  TASSIGN(v58, v59);
  pto::Shape<1, 1, 1, 512, 256> v60 = pto::Shape<1, 1, 1, 512, 256>();
  pto::Stride<16777216, 16777216, 16777216, 1, 4096> v61 = pto::Stride<16777216, 16777216, 16777216, 1, 4096>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN> v62 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN>(v3 + ((v8 + (unsigned) v6 * (unsigned) v12) + v8 * (unsigned) v14 + (unsigned) v7 * (unsigned) v15), v60, v61);
  TLOAD(v58, v62);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v63 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
  uint64_t v64 = (uint64_t) v21;
  TASSIGN(v63, v64);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  for (size_t v65 = v24; v65 < v23; v65 += v22) {
    int32_t v66 = (int32_t) v65;
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v67 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v68 = (uint64_t) v18;
    TASSIGN(v67, v68);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
    pipe_barrier(PIPE_MTE1);
    TEXTRACT(v67, v56, v10, v65);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
    uint64_t v70 = (uint64_t) v21;
    TASSIGN(v69, v70);
    TEXTRACT(v69, v58, v65, v10);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
    uint64_t v72 = (uint64_t) v21;
    TASSIGN(v71, v72);
    int32_t v73 = (int32_t) ((uint32_t) v66 + (uint32_t) v9);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
    TEXTRACT(v71, v56, v10, v73);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v74 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
    uint64_t v75 = (uint64_t) v17;
    TASSIGN(v74, v75);
    TEXTRACT(v74, v58, v73, v10);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    if (v66 == v10) {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v76 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v77 = (uint64_t) v21;
      TASSIGN(v76, v77);
      pipe_barrier(PIPE_M);
      TMATMUL(v76, v67, v69);
    } else {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v78 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v79 = (uint64_t) v21;
      TASSIGN(v78, v79);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v78, v78, v67, v69);
    };
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
    Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v80 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
    uint64_t v81 = (uint64_t) v21;
    TASSIGN(v80, v81);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    TMATMUL_ACC(v80, v80, v71, v74);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  for (size_t v82 = v23; v82 < ((size_t) v15); v82 += v23) {
    int32_t v83 = (int32_t) v82;
    Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
    uint64_t v85 = (uint64_t) v21;
    TASSIGN(v84, v85);
    pto::Shape<1, 1, 1, 16, 512> v86 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v87 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v88 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v8 + v8 * (unsigned) v15 + (unsigned) v83 * (unsigned) v14), v86, v87);
    pipe_barrier(PIPE_MTE2);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    TLOAD(v84, v88);
    Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v89 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
    uint64_t v90 = (uint64_t) v21;
    TASSIGN(v89, v90);
    pipe_barrier(PIPE_MTE2);
    TLOAD(v89, v88);
    Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v91 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v92 = (uint64_t) v20;
    TASSIGN(v91, v92);
    pto::Shape<1, 1, 1, 512, 256> v93 = pto::Shape<1, 1, 1, 512, 256>();
    pto::Stride<16777216, 16777216, 16777216, 1, 4096> v94 = pto::Stride<16777216, 16777216, 16777216, 1, 4096>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN> v95 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN>(v2 + ((v8 + (unsigned) v6 * (unsigned) v12) + (unsigned) v83 * (unsigned) v14 + (unsigned) v7 * (unsigned) v15), v93, v94);
    TLOAD(v91, v95);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
    for (size_t v96 = v24; v96 < v23; v96 += v22) {
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v97 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
      uint64_t v98 = (uint64_t) v18;
      TASSIGN(v97, v98);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      TEXTRACT(v97, v89, v10, v96);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v99 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
      uint64_t v100 = (uint64_t) v21;
      TASSIGN(v99, v100);
      TEXTRACT(v99, v91, v96, v10);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v101 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
      uint64_t v102 = (uint64_t) v21;
      TASSIGN(v101, v102);
      int32_t v103 = (int32_t) ((uint32_t) ((int32_t) v96) + (uint32_t) v9);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TEXTRACT(v101, v89, v10, v103);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
      uint64_t v105 = (uint64_t) v17;
      TASSIGN(v104, v105);
      TEXTRACT(v104, v91, v103, v10);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v106 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v107 = (uint64_t) v19;
      TASSIGN(v106, v107);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v106, v106, v97, v99);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v108 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v109 = (uint64_t) v19;
      TASSIGN(v108, v109);
      pipe_barrier(PIPE_M);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
      TMATMUL_ACC(v108, v108, v101, v104);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    };
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v110 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v11);
    uint64_t v111 = (uint64_t) v21;
    TASSIGN(v110, v111);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID3);
    pipe_barrier(PIPE_MTE2);
    TLOAD(v110, v88);
    Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v112 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v11, v13);
    uint64_t v113 = (uint64_t) v20;
    TASSIGN(v112, v113);
    pto::Shape<1, 1, 1, 512, 256> v114 = pto::Shape<1, 1, 1, 512, 256>();
    pto::Stride<16777216, 16777216, 16777216, 1, 4096> v115 = pto::Stride<16777216, 16777216, 16777216, 1, 4096>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN> v116 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<16777216, 16777216, 16777216, 1, 4096>, pto::Layout::DN>(v3 + ((v8 + (unsigned) v6 * (unsigned) v12) + (unsigned) v83 * (unsigned) v14 + (unsigned) v7 * (unsigned) v15), v114, v115);
    TLOAD(v112, v116);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    for (size_t v117 = v24; v117 < v23; v117 += v22) {
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v118 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
      uint64_t v119 = (uint64_t) v18;
      TASSIGN(v118, v119);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TEXTRACT(v118, v110, v10, v117);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v120 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
      uint64_t v121 = (uint64_t) v21;
      TASSIGN(v120, v121);
      TEXTRACT(v120, v112, v117, v10);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v122 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v16, v9);
      uint64_t v123 = (uint64_t) v21;
      TASSIGN(v122, v123);
      int32_t v124 = (int32_t) ((uint32_t) ((int32_t) v117) + (uint32_t) v9);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      TEXTRACT(v122, v110, v10, v124);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v125 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v13);
      uint64_t v126 = (uint64_t) v17;
      TASSIGN(v125, v126);
      TEXTRACT(v125, v112, v124, v10);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v127 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v128 = (uint64_t) v21;
      TASSIGN(v127, v128);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v127, v127, v118, v120);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v129 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v16, v13);
      uint64_t v130 = (uint64_t) v21;
      TASSIGN(v129, v130);
      pipe_barrier(PIPE_M);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
      TMATMUL_ACC(v129, v129, v122, v125);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    };
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v131 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v132 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v133 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v4 + ((v8 + v8 * (unsigned) v15) + v8 * (unsigned) v13 + v8 * (unsigned) v14), v131, v132);
  wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  TSTORE(v133, v37);
  pto::Shape<1, 1, 1, 16, 256> v134 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v135 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v136 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v5 + ((v8 + v8 * (unsigned) v15) + v8 * (unsigned) v13 + v8 * (unsigned) v14), v134, v135);
  TSTORE(v136, v63);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID2);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: recv_x_tile_i8_inline75__rv_v2
    __gm__ Tensor* recv_x_tile_i8_inline75__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* recv_x_tile_i8_inline75__rv_v2 = reinterpret_cast<__gm__ int8_t*>(recv_x_tile_i8_inline75__rv_v2_tensor->buffer.addr) + recv_x_tile_i8_inline75__rv_v2_tensor->start_offset;

    // Unpack tensor: expert_w1__ssa_v0
    __gm__ Tensor* expert_w1__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* expert_w1__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(expert_w1__ssa_v0_tensor->buffer.addr) + expert_w1__ssa_v0_tensor->start_offset;

    // Unpack tensor: expert_w3__ssa_v0
    __gm__ Tensor* expert_w3__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* expert_w3__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(expert_w3__ssa_v0_tensor->buffer.addr) + expert_w3__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* ret0__out = reinterpret_cast<__gm__ int32_t*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack tensor: ret1__out
    __gm__ Tensor* ret1__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ int32_t* ret1__out = reinterpret_cast<__gm__ int32_t*>(ret1__out_tensor->buffer.addr) + ret1__out_tensor->start_offset;

    // Unpack scalar: local_i_inline67__idx_v0
    union { uint64_t u64; int64_t val; } local_i_inline67__idx_v0_conv;
    local_i_inline67__idx_v0_conv.u64 = args[5];
    int64_t local_i_inline67__idx_v0 = local_i_inline67__idx_v0_conv.val;

    // Unpack scalar: n0_inline72__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline72__idx_v0_conv;
    n0_inline72__idx_v0_conv.u64 = args[6];
    int64_t n0_inline72__idx_v0 = n0_inline72__idx_v0_conv.val;

    // Forward to ptoas-generated function
    exp_gate_up_matmul(recv_x_tile_i8_inline75__rv_v2, expert_w1__ssa_v0, expert_w3__ssa_v0, ret0__out, ret1__out, local_i_inline67__idx_v0, n0_inline72__idx_v0);
}
