// Kernel Function: sh_gate_up_matmul
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void sh_gate_up_matmul(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int8_t* v3, __gm__ int32_t* v4, __gm__ int32_t* v5, int32_t v6) {
  unsigned v7 = 0;
  const int32_t v8 = 128;
  const int32_t v9 = 0;
  const int32_t v10 = 512;
  const int32_t v11 = 256;
  const int32_t v12 = 1;
  const int32_t v13 = 4096;
  const int32_t v14 = 16;
  const int64_t v15 = 32768;
  const int64_t v16 = 2048;
  const int64_t v17 = 16384;
  const int64_t v18 = 139264;
  const int64_t v19 = 8192;
  const int64_t v20 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  size_t v21 = (size_t) v11;
  size_t v22 = (size_t) v10;
  size_t v23 = (size_t) v9;
  Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v24 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v10);
  uint64_t v25 = (uint64_t) v20;
  TASSIGN(v24, v25);
  pto::Shape<1, 1, 1, 16, 512> v26 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v27 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v28 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v7 + v7 * (unsigned) v13 + v7 * (unsigned) v12), v26, v27);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  TLOAD(v24, v28);
  Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v29 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v10, v11);
  uint64_t v30 = (uint64_t) v19;
  TASSIGN(v29, v30);
  pto::Shape<1, 1, 1, 512, 256> v31 = pto::Shape<1, 1, 1, 512, 256>();
  pto::Stride<512, 512, 512, 1, 4096> v32 = pto::Stride<512, 512, 512, 1, 4096>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v33 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v2 + (v7 + v7 * (unsigned) v12 + (unsigned) v6 * (unsigned) v13), v31, v32);
  TLOAD(v29, v33);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v10, v11);
  uint64_t v35 = (uint64_t) v18;
  TASSIGN(v34, v35);
  pto::Shape<1, 1, 1, 512, 256> v36 = pto::Shape<1, 1, 1, 512, 256>();
  pto::Stride<512, 512, 512, 1, 4096> v37 = pto::Stride<512, 512, 512, 1, 4096>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v38 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v3 + (v7 + v7 * (unsigned) v12 + (unsigned) v6 * (unsigned) v13), v36, v37);
  TLOAD(v34, v38);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v39 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
  uint64_t v40 = (uint64_t) v17;
  TASSIGN(v39, v40);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  for (size_t v41 = v23; v41 < v22; v41 += v21) {
    int32_t v42 = (int32_t) v41;
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
    uint64_t v44 = (uint64_t) v16;
    TASSIGN(v43, v44);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    pipe_barrier(PIPE_MTE1);
    TEXTRACT(v43, v24, v9, v41);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
    uint64_t v46 = (uint64_t) v20;
    TASSIGN(v45, v46);
    TEXTRACT(v45, v29, v41, v9);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
    uint64_t v48 = (uint64_t) v20;
    TASSIGN(v47, v48);
    int32_t v49 = (int32_t) ((uint32_t) v42 + (uint32_t) v8);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    TEXTRACT(v47, v24, v9, v49);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v50 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
    uint64_t v51 = (uint64_t) v15;
    TASSIGN(v50, v51);
    TEXTRACT(v50, v29, v49, v9);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    if (v42 == v9) {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v52 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v53 = (uint64_t) v17;
      TASSIGN(v52, v53);
      pipe_barrier(PIPE_M);
      TMATMUL(v52, v43, v45);
    } else {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v54 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v55 = (uint64_t) v17;
      TASSIGN(v54, v55);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v54, v54, v43, v45);
    };
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v57 = (uint64_t) v17;
    TASSIGN(v56, v57);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    TMATMUL_ACC(v56, v56, v47, v50);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v58 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
  uint64_t v59 = (uint64_t) v20;
  TASSIGN(v58, v59);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  for (size_t v60 = v23; v60 < v22; v60 += v21) {
    int32_t v61 = (int32_t) v60;
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
    uint64_t v63 = (uint64_t) v16;
    TASSIGN(v62, v63);
    pipe_barrier(PIPE_MTE1);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
    TEXTRACT(v62, v24, v9, v60);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
    uint64_t v65 = (uint64_t) v20;
    TASSIGN(v64, v65);
    TEXTRACT(v64, v34, v60, v9);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
    uint64_t v67 = (uint64_t) v20;
    TASSIGN(v66, v67);
    int32_t v68 = (int32_t) ((uint32_t) v61 + (uint32_t) v8);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
    TEXTRACT(v66, v24, v9, v68);
    Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
    uint64_t v70 = (uint64_t) v15;
    TASSIGN(v69, v70);
    TEXTRACT(v69, v34, v68, v9);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
    if (v61 == v9) {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v72 = (uint64_t) v20;
      TASSIGN(v71, v72);
      pipe_barrier(PIPE_M);
      TMATMUL(v71, v62, v64);
    } else {
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v74 = (uint64_t) v20;
      TASSIGN(v73, v74);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v73, v73, v62, v64);
    };
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
    Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v75 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
    uint64_t v76 = (uint64_t) v20;
    TASSIGN(v75, v76);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
    TMATMUL_ACC(v75, v75, v66, v69);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID5);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  for (size_t v77 = v22; v77 < ((size_t) v13); v77 += v22) {
    int32_t v78 = (int32_t) v77;
    Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v79 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v10);
    uint64_t v80 = (uint64_t) v20;
    TASSIGN(v79, v80);
    pto::Shape<1, 1, 1, 16, 512> v81 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v82 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v83 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v7 + v7 * (unsigned) v13 + (unsigned) v78 * (unsigned) v12), v81, v82);
    pipe_barrier(PIPE_MTE2);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    TLOAD(v79, v83);
    Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v84 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v10, v11);
    uint64_t v85 = (uint64_t) v19;
    TASSIGN(v84, v85);
    pto::Shape<1, 1, 1, 512, 256> v86 = pto::Shape<1, 1, 1, 512, 256>();
    pto::Stride<512, 512, 512, 1, 4096> v87 = pto::Stride<512, 512, 512, 1, 4096>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v88 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v2 + (v7 + (unsigned) v78 * (unsigned) v12 + (unsigned) v6 * (unsigned) v13), v86, v87);
    TLOAD(v84, v88);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v89 = Tile<TileType::Mat, int8_t, 512, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v10, v11);
    uint64_t v90 = (uint64_t) v18;
    TASSIGN(v89, v90);
    pto::Shape<1, 1, 1, 512, 256> v91 = pto::Shape<1, 1, 1, 512, 256>();
    pto::Stride<512, 512, 512, 1, 4096> v92 = pto::Stride<512, 512, 512, 1, 4096>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v93 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 256>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v3 + (v7 + (unsigned) v78 * (unsigned) v12 + (unsigned) v6 * (unsigned) v13), v91, v92);
    TLOAD(v89, v93);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID2);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
    for (size_t v94 = v23; v94 < v22; v94 += v21) {
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v95 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
      uint64_t v96 = (uint64_t) v16;
      TASSIGN(v95, v96);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      TEXTRACT(v95, v79, v9, v94);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v97 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
      uint64_t v98 = (uint64_t) v20;
      TASSIGN(v97, v98);
      TEXTRACT(v97, v84, v94, v9);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v99 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
      uint64_t v100 = (uint64_t) v20;
      TASSIGN(v99, v100);
      int32_t v101 = (int32_t) ((uint32_t) ((int32_t) v94) + (uint32_t) v8);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TEXTRACT(v99, v79, v9, v101);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v102 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
      uint64_t v103 = (uint64_t) v15;
      TASSIGN(v102, v103);
      TEXTRACT(v102, v84, v101, v9);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v104 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v105 = (uint64_t) v17;
      TASSIGN(v104, v105);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID4);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v104, v104, v95, v97);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v106 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v107 = (uint64_t) v17;
      TASSIGN(v106, v107);
      pipe_barrier(PIPE_M);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID5);
      TMATMUL_ACC(v106, v106, v99, v102);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    };
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID7);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID3);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    for (size_t v108 = v23; v108 < v22; v108 += v21) {
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v109 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
      uint64_t v110 = (uint64_t) v16;
      TASSIGN(v109, v110);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TEXTRACT(v109, v79, v9, v108);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v111 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
      uint64_t v112 = (uint64_t) v20;
      TASSIGN(v111, v112);
      TEXTRACT(v111, v89, v108, v9);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
      Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v113 = Tile<TileType::Left, int8_t, 16, 128, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v14, v8);
      uint64_t v114 = (uint64_t) v20;
      TASSIGN(v113, v114);
      int32_t v115 = (int32_t) ((uint32_t) ((int32_t) v108) + (uint32_t) v8);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
      TEXTRACT(v113, v79, v9, v115);
      Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v116 = Tile<TileType::Right, int8_t, 128, 256, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v8, v11);
      uint64_t v117 = (uint64_t) v15;
      TASSIGN(v116, v117);
      TEXTRACT(v116, v89, v115, v9);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v118 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v119 = (uint64_t) v20;
      TASSIGN(v118, v119);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID6);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v118, v118, v109, v111);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v120 = Tile<TileType::Acc, int32_t, 16, 256, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v14, v11);
      uint64_t v121 = (uint64_t) v20;
      TASSIGN(v120, v121);
      pipe_barrier(PIPE_M);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID7);
      TMATMUL_ACC(v120, v120, v113, v116);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    };
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  }
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID6);
  set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 256> v122 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v123 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v124 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v4 + (v7 + v7 * (unsigned) v11 + v7 * (unsigned) v12), v122, v123);
  wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  TSTORE(v124, v39);
  pto::Shape<1, 1, 1, 16, 256> v125 = pto::Shape<1, 1, 1, 16, 256>();
  pto::Stride<4096, 4096, 4096, 256, 1> v126 = pto::Stride<4096, 4096, 4096, 256, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND> v127 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 256>, pto::Stride<4096, 4096, 4096, 256, 1>, pto::Layout::ND>(v5 + (v7 + v7 * (unsigned) v11 + v7 * (unsigned) v12), v125, v126);
  TSTORE(v127, v58);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: x_local_i8_inline43__rv_v2
    __gm__ Tensor* x_local_i8_inline43__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* x_local_i8_inline43__rv_v2 = reinterpret_cast<__gm__ int8_t*>(x_local_i8_inline43__rv_v2_tensor->buffer.addr) + x_local_i8_inline43__rv_v2_tensor->start_offset;

    // Unpack tensor: shared_w1__ssa_v0
    __gm__ Tensor* shared_w1__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* shared_w1__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(shared_w1__ssa_v0_tensor->buffer.addr) + shared_w1__ssa_v0_tensor->start_offset;

    // Unpack tensor: shared_w3__ssa_v0
    __gm__ Tensor* shared_w3__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int8_t* shared_w3__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(shared_w3__ssa_v0_tensor->buffer.addr) + shared_w3__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ int32_t* ret0__out = reinterpret_cast<__gm__ int32_t*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack tensor: ret1__out
    __gm__ Tensor* ret1__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[4]);
    __gm__ int32_t* ret1__out = reinterpret_cast<__gm__ int32_t*>(ret1__out_tensor->buffer.addr) + ret1__out_tensor->start_offset;

    // Unpack scalar: n0_inline113__idx_v0
    union { uint64_t u64; int64_t val; } n0_inline113__idx_v0_conv;
    n0_inline113__idx_v0_conv.u64 = args[5];
    int64_t n0_inline113__idx_v0 = n0_inline113__idx_v0_conv.val;

    // Forward to ptoas-generated function
    sh_gate_up_matmul(x_local_i8_inline43__rv_v2, shared_w1__ssa_v0, shared_w3__ssa_v0, ret0__out, ret1__out, n0_inline113__idx_v0);
}
