// Kernel Function: sh_w2_matmul
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"


using namespace pto;


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}

static __aicore__ void sh_w2_matmul(__gm__ int8_t* v1, __gm__ int8_t* v2, __gm__ int32_t* v3, int32_t v4) {
  unsigned v5 = 0;
  const int32_t v6 = 64;
  const int32_t v7 = 128;
  const int32_t v8 = 0;
  const int32_t v9 = 512;
  const int32_t v10 = 1;
  const int32_t v11 = 4096;
  const int32_t v12 = 16;
  const int64_t v13 = 32768;
  const int64_t v14 = 1024;
  const int64_t v15 = 8192;
  const int64_t v16 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  size_t v17 = (size_t) v9;
  size_t v18 = (size_t) v8;
  size_t v19 = (size_t) v7;
  Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v20 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v9);
  uint64_t v21 = (uint64_t) v16;
  TASSIGN(v20, v21);
  pto::Shape<1, 1, 1, 16, 512> v22 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<65536, 65536, 65536, 4096, 1> v23 = pto::Stride<65536, 65536, 65536, 4096, 1>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v24 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v11 + v5 * (unsigned) v10), v22, v23);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  TLOAD(v20, v24);
  Tile<TileType::Mat, int8_t, 512, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v25 = Tile<TileType::Mat, int8_t, 512, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v9);
  uint64_t v26 = (uint64_t) v15;
  TASSIGN(v25, v26);
  pto::Shape<1, 1, 1, 512, 512> v27 = pto::Shape<1, 1, 1, 512, 512>();
  pto::Stride<512, 512, 512, 1, 4096> v28 = pto::Stride<512, 512, 512, 1, 4096>();
  GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 512>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v29 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 512>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v2 + (v5 + v5 * (unsigned) v10 + (unsigned) v4 * (unsigned) v11), v27, v28);
  TLOAD(v25, v29);
  set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v30 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
  uint64_t v31 = (uint64_t) v16;
  TASSIGN(v30, v31);
  wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
  for (size_t v32 = v18; v32 < v17; v32 += v19) {
    int32_t v33 = (int32_t) v32;
    Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v34 = Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v35 = (uint64_t) v16;
    TASSIGN(v34, v35);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    pipe_barrier(PIPE_MTE1);
    TEXTRACT(v34, v20, v8, v32);
    Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v36 = Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
    uint64_t v37 = (uint64_t) v16;
    TASSIGN(v36, v37);
    TEXTRACT(v36, v25, v32, v8);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v38 = Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
    uint64_t v39 = (uint64_t) v14;
    TASSIGN(v38, v39);
    int32_t v40 = (int32_t) ((uint32_t) v33 + (uint32_t) v6);
    wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
    TEXTRACT(v38, v20, v8, v40);
    Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v41 = Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
    uint64_t v42 = (uint64_t) v13;
    TASSIGN(v41, v42);
    TEXTRACT(v41, v25, v40, v8);
    set_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
    if (v33 == v8) {
      Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v43 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
      uint64_t v44 = (uint64_t) v16;
      TASSIGN(v43, v44);
      pipe_barrier(PIPE_M);
      TMATMUL(v43, v34, v36);
    } else {
      Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v45 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
      uint64_t v46 = (uint64_t) v16;
      TASSIGN(v45, v46);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v45, v45, v34, v36);
    };
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
    Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v47 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
    uint64_t v48 = (uint64_t) v16;
    TASSIGN(v47, v48);
    pipe_barrier(PIPE_M);
    wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID1);
    TMATMUL_ACC(v47, v47, v38, v41);
    set_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  }
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID2);
  for (size_t v49 = v17; v49 < ((size_t) v11); v49 += v17) {
    int32_t v50 = (int32_t) v49;
    Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v51 = Tile<TileType::Mat, int8_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v9);
    uint64_t v52 = (uint64_t) v16;
    TASSIGN(v51, v52);
    pto::Shape<1, 1, 1, 16, 512> v53 = pto::Shape<1, 1, 1, 16, 512>();
    pto::Stride<65536, 65536, 65536, 4096, 1> v54 = pto::Stride<65536, 65536, 65536, 4096, 1>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND> v55 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<65536, 65536, 65536, 4096, 1>, pto::Layout::ND>(v1 + (v5 + v5 * (unsigned) v11 + (unsigned) v50 * (unsigned) v10), v53, v54);
    pipe_barrier(PIPE_MTE2);
    wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
    TLOAD(v51, v55);
    Tile<TileType::Mat, int8_t, 512, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v56 = Tile<TileType::Mat, int8_t, 512, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v9, v9);
    uint64_t v57 = (uint64_t) v15;
    TASSIGN(v56, v57);
    pto::Shape<1, 1, 1, 512, 512> v58 = pto::Shape<1, 1, 1, 512, 512>();
    pto::Stride<512, 512, 512, 1, 4096> v59 = pto::Stride<512, 512, 512, 1, 4096>();
    GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 512>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN> v60 = GlobalTensor<int8_t, pto::Shape<1, 1, 1, 512, 512>, pto::Stride<512, 512, 512, 1, 4096>, pto::Layout::DN>(v2 + (v5 + (unsigned) v50 * (unsigned) v10 + (unsigned) v4 * (unsigned) v11), v58, v59);
    TLOAD(v56, v60);
    set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID1);
    for (size_t v61 = v18; v61 < v17; v61 += v19) {
      Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v62 = Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
      uint64_t v63 = (uint64_t) v16;
      TASSIGN(v62, v63);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
      TEXTRACT(v62, v51, v8, v61);
      Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v64 = Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
      uint64_t v65 = (uint64_t) v16;
      TASSIGN(v64, v65);
      TEXTRACT(v64, v56, v61, v8);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
      Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null> v66 = Tile<TileType::Left, int8_t, 16, 64, BLayout::RowMajor, -1, -1, SLayout::RowMajor, 512, PadValue::Null, CompactMode::Null>(v12, v6);
      uint64_t v67 = (uint64_t) v14;
      TASSIGN(v66, v67);
      int32_t v68 = (int32_t) ((uint32_t) ((int32_t) v61) + (uint32_t) v6);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
      TEXTRACT(v66, v51, v8, v68);
      Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null> v69 = Tile<TileType::Right, int8_t, 64, 512, BLayout::RowMajor, -1, -1, SLayout::ColMajor, 512, PadValue::Null, CompactMode::Null>(v6, v9);
      uint64_t v70 = (uint64_t) v13;
      TASSIGN(v69, v70);
      TEXTRACT(v69, v56, v68, v8);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
      Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v71 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
      uint64_t v72 = (uint64_t) v16;
      TASSIGN(v71, v72);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID2);
      pipe_barrier(PIPE_M);
      TMATMUL_ACC(v71, v71, v62, v64);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
      Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null> v73 = Tile<TileType::Acc, int32_t, 16, 512, BLayout::ColMajor, -1, -1, SLayout::RowMajor, 1024, PadValue::Null, CompactMode::Null>(v12, v9);
      uint64_t v74 = (uint64_t) v16;
      TASSIGN(v73, v74);
      pipe_barrier(PIPE_M);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID3);
      TMATMUL_ACC(v73, v73, v66, v69);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
    };
    set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  }
  set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  pto::Shape<1, 1, 1, 16, 512> v75 = pto::Shape<1, 1, 1, 16, 512>();
  pto::Stride<8192, 8192, 8192, 512, 1> v76 = pto::Stride<8192, 8192, 8192, 512, 1>();
  GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND> v77 = GlobalTensor<int32_t, pto::Shape<1, 1, 1, 16, 512>, pto::Stride<8192, 8192, 8192, 512, 1>, pto::Layout::ND>(v3 + (v5 + v5 * (unsigned) v9 + v5 * (unsigned) v10), v75, v76);
  wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
  TSTORE(v77, v30);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID1);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID3);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID4);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: sh_tile_i8_inline126__rv_v2
    __gm__ Tensor* sh_tile_i8_inline126__rv_v2_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ int8_t* sh_tile_i8_inline126__rv_v2 = reinterpret_cast<__gm__ int8_t*>(sh_tile_i8_inline126__rv_v2_tensor->buffer.addr) + sh_tile_i8_inline126__rv_v2_tensor->start_offset;

    // Unpack tensor: shared_w2__ssa_v0
    __gm__ Tensor* shared_w2__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ int8_t* shared_w2__ssa_v0 = reinterpret_cast<__gm__ int8_t*>(shared_w2__ssa_v0_tensor->buffer.addr) + shared_w2__ssa_v0_tensor->start_offset;

    // Unpack tensor: ret0__out
    __gm__ Tensor* ret0__out_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ int32_t* ret0__out = reinterpret_cast<__gm__ int32_t*>(ret0__out_tensor->buffer.addr) + ret0__out_tensor->start_offset;

    // Unpack scalar: d0_inline64__idx_v0
    union { uint64_t u64; int64_t val; } d0_inline64__idx_v0_conv;
    d0_inline64__idx_v0_conv.u64 = args[3];
    int64_t d0_inline64__idx_v0 = d0_inline64__idx_v0_conv.val;

    // Forward to ptoas-generated function
    sh_w2_matmul(sh_tile_i8_inline126__rv_v2, shared_w2__ssa_v0, ret0__out, d0_inline64__idx_v0);
}
