/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

// Captured from a PyPTO-emitted `tests/st/runtime/ops/test_scatter.py::TestScatterIndexForm::test_scatter_fp16[a2a3]`
// run via `pytest --save-kernels --kernels-dir`. ONE DELTA from the original
// ptoas output: an explicit `set_flag(PIPE_S, PIPE_V, EVENT_ID1)` +
// `wait_flag(PIPE_S, PIPE_V, EVENT_ID1)` pair was inserted right after the
// `TCI` that initializes the row-index iota on PIPE_S — without it the
// downstream `TMULS` on PIPE_V races the TCI write and the high lanes
// (positions 14, 15) of the row-offset col vector come out as zero,
// collapsing rows 14/15 of the scatter output onto row 0. This is the race
// behind issue #967; see `docs/investigations/2026-06-scatter-race-a2a3.md`
// for the full bisect and the falsified runtime-side hypotheses. The fix
// belongs in PyPTO codegen; this snapshot ships the patched form so the
// simpler runtime can be regression-tested against a correct AIV-only
// column-scatter kernel.

// Kernel Function: main_incore_0
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#if defined(__CPU_SIM)
#define __aicore__
#else
#define __aicore__ [aicore]
#endif
#endif

#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
    kBarrierAll = 0,
    kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
    switch (mode) {
    case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
        set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
        break;
    case PTOAutoSyncTailMode::kBarrierAll:
    default:
        pipe_barrier(PIPE_ALL);
        break;
    }
}

static __aicore__ void main_incore_0(__gm__ half *v1, __gm__ int16_t *v2, __gm__ half *v3, __gm__ half *v4) {
    CmpMode v5 = CmpMode::NE;
    unsigned v6 = 0;
    const int32_t v7 = 4;
    const half v8 = 1.0f;
    const half v9 = 0.0f;
    const int16_t v10 = 32;
    const int16_t v11 = 0;
    const int32_t v12 = 1;
    const int32_t v13 = 32;
    const int32_t v14 = 16;
    const int64_t v15 = 2560;
    const int64_t v16 = 2048;
    const int64_t v17 = 1024;
    const int64_t v18 = 0;
    const int64_t v19 = 4640;
    const int64_t v20 = 4128;
    const int64_t v21 = 3616;
    const int64_t v22 = 2592;
    using T = float;

#if defined(__DAV_VEC__)
    set_mask_norm();
    set_vector_mask(-1, -1);
    Tile<
        TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v23 = Tile<
            TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v13);
    uint64_t v24 = (uint64_t)v22;
    TASSIGN(v23, v24);
    pto::Shape<1, 1, 1, 16, 32> v25 = pto::Shape<1, 1, 1, 16, 32>();
    pto::Stride<512, 512, 512, 32, 1> v26 = pto::Stride<512, 512, 512, 32, 1>();
    GlobalTensor<half, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v27 =
        GlobalTensor<half, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(
            v1 + (v6 + v6 * (unsigned)v13 + v6 * (unsigned)v12), v25, v26
        );
    TLOAD(v23, v27);
    Tile<
        TileType::Vec, int16_t, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v28 = Tile<
            TileType::Vec, int16_t, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v14);
    uint64_t v29 = (uint64_t)v21;
    TASSIGN(v28, v29);
    pto::Shape<1, 1, 1, 16, 16> v30 = pto::Shape<1, 1, 1, 16, 16>();
    pto::Stride<256, 256, 256, 16, 1> v31 = pto::Stride<256, 256, 256, 16, 1>();
    GlobalTensor<int16_t, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND> v32 =
        GlobalTensor<int16_t, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND>(
            v2 + (v6 + v6 * (unsigned)v14 + v6 * (unsigned)v12), v30, v31
        );
    TLOAD(v28, v32);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    Tile<
        TileType::Vec, half, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v33 = Tile<
            TileType::Vec, half, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v14);
    uint64_t v34 = (uint64_t)v20;
    TASSIGN(v33, v34);
    pto::Shape<1, 1, 1, 16, 16> v35 = pto::Shape<1, 1, 1, 16, 16>();
    pto::Stride<256, 256, 256, 16, 1> v36 = pto::Stride<256, 256, 256, 16, 1>();
    GlobalTensor<half, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND> v37 =
        GlobalTensor<half, pto::Shape<1, 1, 1, 16, 16>, pto::Stride<256, 256, 256, 16, 1>, pto::Layout::ND>(
            v3 + (v6 + v6 * (unsigned)v14 + v6 * (unsigned)v12), v35, v36
        );
    TLOAD(v33, v37);
    set_flag(PIPE_MTE2, PIPE_S, EVENT_ID0);
    Tile<
        TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v38 = Tile<
            TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v14);
    uint64_t v39 = (uint64_t)v19;
    TASSIGN(v38, v39);
    TCI<Tile<
            TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>,
        int16_t, 0>(v38, v11);
    // ISSUE-967 FIX (not part of ptoas output): TCI just wrote the iota on
    // PIPE_S into the UB buffer at offset v19; the TMULS below runs on PIPE_V
    // and reads back the same buffer. The PyPTO-emitted `pipe_barrier(PIPE_V)`
    // a few lines down is a no-op (PIPE_V has nothing in flight yet), so
    // without an S->V handshake TMULS can fire before TCI's iota write
    // retires, leaving the high lanes (positions 14, 15) holding stale UB
    // data (often zero). That zeroes v44[14] / v44[15] and collapses the
    // high-row scatter writes onto row 0 — exactly the bug fingerprint.
    set_flag(PIPE_S, PIPE_V, EVENT_ID1);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID1);
    Tile<
        TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v40 = Tile<
            TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v14);
    uint64_t v41 = (uint64_t)v19;
    TASSIGN(v40, v41);
    Tile<
        TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v42 = Tile<
            TileType::Vec, int16_t, 1, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v14);
    uint64_t v43 = (uint64_t)v19;
    TASSIGN(v42, v43);
    pipe_barrier(PIPE_V);
    TMULS(v42, v40, v10);
    Tile<
        TileType::Vec, int16_t, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v44 = Tile<
            TileType::Vec, int16_t, 16, 1, BLayout::ColMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v12);
    uint64_t v45 = (uint64_t)v19;
    TASSIGN(v44, v45);
    Tile<
        TileType::Vec, int16_t, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v46 = Tile<
            TileType::Vec, int16_t, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v14);
    uint64_t v47 = (uint64_t)v21;
    TASSIGN(v46, v47);
    pipe_barrier(PIPE_V);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
    TROWEXPANDADD(v46, v28, v44);
    Tile<
        TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v48 = Tile<
            TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v13);
    uint64_t v49 = (uint64_t)v18;
    TASSIGN(v48, v49);
    TEXPANDS(v48, v9);
    set_flag(PIPE_V, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE2, PIPE_S, EVENT_ID0);
    TSCATTER(v48, v33, v46);
    set_flag(PIPE_S, PIPE_V, EVENT_ID0);
    Tile<
        TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v50 = Tile<
            TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v13);
    uint64_t v51 = (uint64_t)v17;
    TASSIGN(v50, v51);
    TEXPANDS(v50, v9);
    Tile<
        TileType::Vec, half, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v52 = Tile<
            TileType::Vec, half, 16, 16, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v14);
    uint64_t v53 = (uint64_t)v20;
    TASSIGN(v52, v53);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
    TEXPANDS(v52, v8);
    set_flag(PIPE_V, PIPE_S, EVENT_ID1);
    wait_flag(PIPE_V, PIPE_S, EVENT_ID1);
    TSCATTER(v50, v52, v46);
    set_flag(PIPE_S, PIPE_V, EVENT_ID1);
    Tile<
        TileType::Vec, uint8_t, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v54 = Tile<
            TileType::Vec, uint8_t, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v7);
    uint64_t v55 = (uint64_t)v16;
    TASSIGN(v54, v55);
    wait_flag(PIPE_S, PIPE_V, EVENT_ID1);
    TCMPS(v54, v50, v9, v5);
    Tile<
        TileType::Vec, uint8_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v56 = Tile<
            TileType::Vec, uint8_t, 1, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v12, v13);
    uint64_t v57 = (uint64_t)v15;
    TASSIGN(v56, v57);
    Tile<
        TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
        CompactMode::Null>
        v58 = Tile<
            TileType::Vec, half, 16, 32, BLayout::RowMajor, -1, -1, SLayout::NoneBox, 512, PadValue::Null,
            CompactMode::Null>(v14, v13);
    uint64_t v59 = (uint64_t)v22;
    TASSIGN(v58, v59);
    pipe_barrier(PIPE_V);
    TSEL(v58, v54, v48, v23, v56);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    pto::Shape<1, 1, 1, 16, 32> v60 = pto::Shape<1, 1, 1, 16, 32>();
    pto::Stride<512, 512, 512, 32, 1> v61 = pto::Stride<512, 512, 512, 32, 1>();
    GlobalTensor<half, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND> v62 =
        GlobalTensor<half, pto::Shape<1, 1, 1, 16, 32>, pto::Stride<512, 512, 512, 32, 1>, pto::Layout::ND>(
            v4 + (v6 + v6 * (unsigned)v13 + v6 * (unsigned)v12), v60, v61
        );
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
    TSTORE(v62, v58);
#endif  // __DAV_VEC__

    ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
    return;
}
// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t *args) {
    // Unpack tensor: base__ssa_v0
    __gm__ Tensor *base__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor *>(args[0]);
    __gm__ half *base__ssa_v0 =
        reinterpret_cast<__gm__ half *>(base__ssa_v0_tensor->buffer.addr) + base__ssa_v0_tensor->start_offset;

    // Unpack tensor: idx__ssa_v0
    __gm__ Tensor *idx__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor *>(args[1]);
    __gm__ int16_t *idx__ssa_v0 =
        reinterpret_cast<__gm__ int16_t *>(idx__ssa_v0_tensor->buffer.addr) + idx__ssa_v0_tensor->start_offset;

    // Unpack tensor: val__ssa_v0
    __gm__ Tensor *val__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor *>(args[2]);
    __gm__ half *val__ssa_v0 =
        reinterpret_cast<__gm__ half *>(val__ssa_v0_tensor->buffer.addr) + val__ssa_v0_tensor->start_offset;

    // Unpack tensor: output__ssa_v0
    __gm__ Tensor *output__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor *>(args[3]);
    __gm__ half *output__ssa_v0 =
        reinterpret_cast<__gm__ half *>(output__ssa_v0_tensor->buffer.addr) + output__ssa_v0_tensor->start_offset;

    // Forward to ptoas-generated function
    main_incore_0(base__ssa_v0, idx__ssa_v0, val__ssa_v0, output__ssa_v0);
}
