// Orchestration Function: paged_attention
// Generated by PyPTO IR Compiler

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "pto_orchestration_api.h"

#define ARG_PTR_QUERY 0
#define ARG_PTR_KEY_CACHE 1
#define ARG_PTR_VALUE_CACHE 2
#define ARG_PTR_HOST_BLOCK_TABLE 3
#define ARG_PTR_CONTEXT_LENS 4
#define ARG_PTR_OUT 5
#define ARG_PTR_CONFIG 6

// Helper to encode float as uint64_t for scalar params
static uint64_t float_to_u64(float f) {
    union {
        float f32;
        uint64_t u64;
    } conv;
    conv.u64 = 0;  // Clear upper bits
    conv.f32 = f;
    return conv.u64;
}

extern "C" {

__attribute__((visibility("default")))
PTO2OrchestrationConfig aicpu_orchestration_config(uint64_t* args, int arg_count) {
    (void)args;
    (void)arg_count;
    return PTO2OrchestrationConfig{
        .expected_arg_count = 7,
    };
}

__attribute__((visibility("default")))
void aicpu_orchestration_entry(PTO2Runtime* rt, uint64_t* args, int arg_count) {
    (void)arg_count;

    // Extract device pointers
    void* arg_query_ptr = reinterpret_cast<void*>(args[ARG_PTR_QUERY]);
    void* arg_key_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_KEY_CACHE]);
    void* arg_value_cache_ptr = reinterpret_cast<void*>(args[ARG_PTR_VALUE_CACHE]);
    void* arg_host_block_table_ptr = reinterpret_cast<void*>(args[ARG_PTR_HOST_BLOCK_TABLE]);
    void* arg_context_lens_ptr = reinterpret_cast<void*>(args[ARG_PTR_CONTEXT_LENS]);
    void* arg_out_ptr = reinterpret_cast<void*>(args[ARG_PTR_OUT]);
    void* arg_config_ptr = reinterpret_cast<void*>(args[ARG_PTR_CONFIG]);

    // External tensors
    uint64_t query_shapes[2] = {32, 128};
    Tensor ext_query = make_tensor_external(arg_query_ptr, query_shapes, 2, DataType::BFLOAT16);
    uint64_t key_cache_shapes[2] = {8192, 128};
    Tensor ext_key_cache = make_tensor_external(arg_key_cache_ptr, key_cache_shapes, 2, DataType::BFLOAT16);
    uint64_t value_cache_shapes[2] = {8192, 128};
    Tensor ext_value_cache = make_tensor_external(arg_value_cache_ptr, value_cache_shapes, 2, DataType::BFLOAT16);
    uint64_t host_block_table_shapes[1] = {32};
    Tensor ext_host_block_table = make_tensor_external(arg_host_block_table_ptr, host_block_table_shapes, 1, DataType::INT32);
    uint64_t context_lens_shapes[1] = {2};
    Tensor ext_context_lens = make_tensor_external(arg_context_lens_ptr, context_lens_shapes, 1, DataType::INT32);
    uint64_t out_shapes[2] = {32, 128};
    Tensor ext_out = make_tensor_external(arg_out_ptr, out_shapes, 2, DataType::FLOAT32);
    uint64_t config_shapes[1] = {7};
    Tensor ext_config = make_tensor_external(arg_config_ptr, config_shapes, 1, DataType::UINT64);

    uint64_t batch = static_cast<uint64_t*>(arg_config_ptr)[0];
    uint64_t num_heads = static_cast<uint64_t*>(arg_config_ptr)[1];
    uint64_t head_dim = static_cast<uint64_t*>(arg_config_ptr)[3];
    uint64_t block_size = static_cast<uint64_t*>(arg_config_ptr)[4];
    uint64_t block_num = static_cast<uint64_t*>(arg_config_ptr)[5];
    uint64_t q_tile = std::min<uint64_t>(num_heads, static_cast<uint64_t>(128));
    uint64_t q_loop = (((num_heads + q_tile) - static_cast<uint64_t>(1)) / q_tile);
    for (int64_t b_idx = 0; b_idx < batch; b_idx += 1) {
        PTO2_SCOPE(rt) {
            size_t idx_cur_seq = b_idx;
            int32_t cur_seq = static_cast<int32_t*>(arg_context_lens_ptr)[idx_cur_seq];
            uint64_t bn_this_batch = (((static_cast<uint64_t>(cur_seq) + block_size) - static_cast<uint64_t>(1)) / block_size);
            for (int64_t q_idx = 0; q_idx < q_loop; q_idx += 1) {
                PTO2_SCOPE(rt) {
                    int64_t cur_offset = ((b_idx * static_cast<int64_t>(num_heads)) + (q_idx * static_cast<int64_t>(q_tile)));
                    uint64_t oi_shapes[2] = {q_tile, head_dim};
                    Tensor oi = make_tensor(oi_shapes, 2, DataType::FLOAT32);
                    uint64_t li_update_shapes[1] = {q_tile};
                    Tensor li_update = make_tensor(li_update_shapes, 1, DataType::FLOAT32);
                    uint64_t mi_update_shapes[1] = {q_tile};
                    Tensor mi_update = make_tensor(mi_update_shapes, 1, DataType::FLOAT32);

                    // Task 0: kernel_init_inplace
                    PTOParam params_t0[] = {
                        make_output_param(oi),
                        make_output_param(li_update),
                        make_output_param(mi_update),
                    };
                    pto2_rt_submit_task(rt, 0, PTO2_WORKER_VECTOR, params_t0, 3);
                    for (int64_t bn = 0; bn < bn_this_batch; bn += 1) {
                        PTO2_SCOPE(rt) {
                            Tensor qi = ext_query.view({q_tile, head_dim}, {cur_offset, 0});
                            size_t idx_cur_block_idx = ((b_idx * static_cast<int64_t>(block_num)) + bn);
                            int32_t cur_block_idx = static_cast<int32_t*>(arg_host_block_table_ptr)[idx_cur_block_idx];
                            uint64_t valid_len = std::min<uint64_t>(block_size, static_cast<uint64_t>((static_cast<int64_t>(cur_seq) - (bn * static_cast<int64_t>(block_size)))));
                            Tensor kj = ext_key_cache.view({block_size, head_dim}, {(static_cast<uint64_t>(cur_block_idx) * block_size), 0});
                            Tensor vj = ext_value_cache.view({block_size, head_dim}, {(static_cast<uint64_t>(cur_block_idx) * block_size), 0});
                            uint64_t sij_shapes[2] = {q_tile, block_size};
                            Tensor sij = make_tensor(sij_shapes, 2, DataType::FLOAT32);

                            // Task 1: kernel_qk_matmul
                            PTOParam params_t1[] = {
                                make_input_param(qi),
                                make_input_param(kj),
                                make_output_param(sij),
                            };
                            pto2_rt_submit_task(rt, 1, PTO2_WORKER_CUBE, params_t1, 3);
                            Tensor sij_valid = sij.view({q_tile, valid_len}, {0, 0});
                            uint64_t pij_shapes[2] = {q_tile, block_size};
                            Tensor pij = make_tensor(pij_shapes, 2, DataType::BFLOAT16);
                            uint64_t mi_shapes[1] = {q_tile};
                            Tensor mi = make_tensor(mi_shapes, 1, DataType::FLOAT32);
                            uint64_t li_shapes[1] = {q_tile};
                            Tensor li = make_tensor(li_shapes, 1, DataType::FLOAT32);

                            // Task 2: kernel_softmax_prepare
                            PTOParam params_t2[] = {
                                make_input_param(sij_valid),
                                make_scalar_param(float_to_u64(1.000000f)),
                                make_output_param(pij),
                                make_output_param(mi),
                                make_output_param(li),
                            };
                            pto2_rt_submit_task(rt, 2, PTO2_WORKER_VECTOR, params_t2, 5);
                            uint64_t oi_tmp_shapes[2] = {q_tile, head_dim};
                            Tensor oi_tmp = make_tensor(oi_tmp_shapes, 2, DataType::FLOAT32);

                            // Task 3: kernel_pv_matmul
                            PTOParam params_t3[] = {
                                make_input_param(pij),
                                make_input_param(vj),
                                make_output_param(oi_tmp),
                            };
                            pto2_rt_submit_task(rt, 3, PTO2_WORKER_CUBE, params_t3, 3);
                            uint64_t is_first;
                            if ((bn == 0)) {
                                PTO2_SCOPE(rt) {
                                    is_first = 1;
                                }
                            } else {
                                PTO2_SCOPE(rt) {
                                    is_first = 0;
                                }
                            }
                            uint64_t is_last;
                            if ((bn == static_cast<int64_t>((bn_this_batch - static_cast<uint64_t>(1))))) {
                                PTO2_SCOPE(rt) {
                                    is_last = 1;
                                }
                            } else {
                                PTO2_SCOPE(rt) {
                                    is_last = 0;
                                }
                            }
                            Tensor out_view = ext_out.view({q_tile, head_dim}, {cur_offset, 0});

                            // Task 4: kernel_online_update
                            PTOParam params_t4[] = {
                                make_input_param(mi),
                                make_input_param(li),
                                make_input_param(oi_tmp),
                                make_inout_param(mi_update),
                                make_inout_param(li_update),
                                make_inout_param(oi),
                                make_output_param(out_view),
                                make_scalar_param(is_first),
                                make_scalar_param(is_last),
                            };
                            pto2_rt_submit_task(rt, 4, PTO2_WORKER_VECTOR, params_t4, 9);
                        }
                    }
                }
            }
        }
    }
}

}  // extern "C"
