/*
 * Copyright (c) PyPTO Contributors.
 * This program is free software, you can redistribute it and/or modify it under the terms and conditions of
 * CANN Open Software License Agreement Version 2.0 (the "License").
 * Please refer to the License for details. You may not use this file except in compliance with the License.
 * THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND, EITHER EXPRESS OR IMPLIED,
 * INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT, MERCHANTABILITY, OR FITNESS FOR A PARTICULAR PURPOSE.
 * See LICENSE in the root of the software repository for the full text of the License.
 * -----------------------------------------------------------------------------------------------------------
 */

// Captured verbatim from a PyPTO test_scatter_fp16[a2a3] run with
// --save-kernels. Submits a single AIV-only column-scatter task with the
// four-tensor shape (base, idx, val, output). Paired with the AIV kernel in
// kernels/aiv/scatter_aiv.cpp.

// Orchestration Function: main
// Generated by PyPTO IR Compiler

#include "runtime.h"
#include <iostream>

#include <stddef.h>
#include <stdint.h>
#include <stdio.h>

#include "pto_orchestration_api.h"

extern "C" {

__attribute__((visibility("default"))) PTO2OrchestrationConfig
aicpu_orchestration_config(const ChipStorageTaskArgs &orch_args) {
    (void)orch_args;
    return PTO2OrchestrationConfig{
        .expected_arg_count = 4,
    };
}

__attribute__((visibility("default"))) void aicpu_orchestration_entry(const ChipStorageTaskArgs &orch_args) {
    // External tensors
    Tensor ext_base = from_tensor_arg(orch_args.tensor(0));
    Tensor ext_idx = from_tensor_arg(orch_args.tensor(1));
    Tensor ext_val = from_tensor_arg(orch_args.tensor(2));
    Tensor ext_output = from_tensor_arg(orch_args.tensor(3));

    PTO2_SCOPE() {
        // Task 0: main_incore_0
        Arg params_t0;
        params_t0.add_input(ext_base);
        params_t0.add_input(ext_idx);
        params_t0.add_input(ext_val);
        params_t0.add_inout(ext_output);
        rt_submit_aiv_task(0, params_t0);
    }
}

}  // extern "C"
