/**
 * AscendC AddCustom Operator — Reference Source
 *
 * This file documents the AscendC kernel source used for PTO integration.
 * The actual .o is built by build_add_custom.sh.
 *
 * PTO integration requires two adaptations from standard AscendC kernels:
 *
 *   1. NO __global__ attribute — PTO's dispatch loop calls kernels as
 *      subroutines; __global__ generates a prologue that resets AICore
 *      state and never returns, causing a hang.
 *
 *   2. NO GetBlockNum()/GetBlockIdx() partitioning — PTO dispatches each
 *      task to a single core, so the kernel must process all data.
 *      (Framework-launched AscendC launches across all blocks simultaneously.)
 *
 * Calling convention:
 *   extern "C" __aicore__ void add_custom(
 *       GM_ADDR x, GM_ADDR y, GM_ADDR z,
 *       GM_ADDR workspace, GM_ADDR tiling);
 *
 * The PTO wrapper (generated by AscendCCompiler) provides kernel_entry()
 * which unpacks Tensor* args and forwards raw GM addresses to add_custom().
 *
 * Static tiling: totalLength=16384 and tileNum=8 are hardcoded as constexpr.
 * No runtime tiling pointer is needed (workspace and tiling are unused).
 */

// ============================================================================
// The actual source compiled by build_add_custom.sh (reproduced here for
// reference — not compiled by PTO).
// ============================================================================

#if 0  // Not compiled — reference only

#include "kernel_operator.h"

using namespace AscendC;
constexpr int32_t BUFFER_NUM = 2;

class KernelAdd {
public:
    __aicore__ inline KernelAdd() {}
    __aicore__ inline void Init(GM_ADDR x, GM_ADDR y, GM_ADDR z,
                                uint32_t totalLength, uint32_t tileNum)
    {
        // Process ALL data — no GetBlockNum() division (PTO single-core dispatch)
        this->blockLength = totalLength;
        this->tileNum = tileNum;
        this->tileLength = this->blockLength / tileNum / BUFFER_NUM;
        xGm.SetGlobalBuffer((__gm__ DTYPE_X*)x, this->blockLength);
        yGm.SetGlobalBuffer((__gm__ DTYPE_Y*)y, this->blockLength);
        zGm.SetGlobalBuffer((__gm__ DTYPE_Z*)z, this->blockLength);
        pipe.InitBuffer(inQueueX, BUFFER_NUM, this->tileLength * sizeof(DTYPE_X));
        pipe.InitBuffer(inQueueY, BUFFER_NUM, this->tileLength * sizeof(DTYPE_Y));
        pipe.InitBuffer(outQueueZ, BUFFER_NUM, this->tileLength * sizeof(DTYPE_Z));
    }
    __aicore__ inline void Process()
    {
        int32_t loopCount = this->tileNum * BUFFER_NUM;
        for (int32_t i = 0; i < loopCount; i++) {
            CopyIn(i);
            Compute(i);
            CopyOut(i);
        }
    }
private:
    __aicore__ inline void CopyIn(int32_t progress)
    {
        LocalTensor<DTYPE_X> xLocal = inQueueX.AllocTensor<DTYPE_X>();
        LocalTensor<DTYPE_Y> yLocal = inQueueY.AllocTensor<DTYPE_Y>();
        DataCopy(xLocal, xGm[progress * this->tileLength], this->tileLength);
        DataCopy(yLocal, yGm[progress * this->tileLength], this->tileLength);
        inQueueX.EnQue(xLocal);
        inQueueY.EnQue(yLocal);
    }
    __aicore__ inline void Compute(int32_t progress)
    {
        LocalTensor<DTYPE_X> xLocal = inQueueX.DeQue<DTYPE_X>();
        LocalTensor<DTYPE_Y> yLocal = inQueueY.DeQue<DTYPE_Y>();
        LocalTensor<DTYPE_Z> zLocal = outQueueZ.AllocTensor<DTYPE_Z>();
        Add(zLocal, xLocal, yLocal, this->tileLength);
        outQueueZ.EnQue<DTYPE_Z>(zLocal);
        inQueueX.FreeTensor(xLocal);
        inQueueY.FreeTensor(yLocal);
    }
    __aicore__ inline void CopyOut(int32_t progress)
    {
        LocalTensor<DTYPE_Z> zLocal = outQueueZ.DeQue<DTYPE_Z>();
        DataCopy(zGm[progress * this->tileLength], zLocal, this->tileLength);
        outQueueZ.FreeTensor(zLocal);
    }
private:
    TPipe pipe;
    TQue<QuePosition::VECIN, BUFFER_NUM> inQueueX, inQueueY;
    TQue<QuePosition::VECOUT, BUFFER_NUM> outQueueZ;
    GlobalTensor<DTYPE_X> xGm;
    GlobalTensor<DTYPE_Y> yGm;
    GlobalTensor<DTYPE_Z> zGm;
    uint32_t blockLength;
    uint32_t tileNum;
    uint32_t tileLength;
};

// No __global__ — called as subroutine from PTO wrapper's kernel_entry
extern "C" __aicore__ void add_custom(
    GM_ADDR x, GM_ADDR y, GM_ADDR z,
    GM_ADDR workspace, GM_ADDR tiling)
{
    constexpr uint32_t totalLength = 16384;
    constexpr uint32_t tileNum = 8;
    KernelAdd op;
    op.Init(x, y, z, totalLength, tileNum);
    op.Process();
}

#endif
